-- 1. Atualizar a constraint de número de lições para permitir até 30 lições por tema (caso ainda não tenha sido aplicada)
ALTER TABLE "public"."dev_lessons" 
  DROP CONSTRAINT IF EXISTS "dev_lessons_lesson_number_check",
  ADD CONSTRAINT "dev_lessons_lesson_number_check" CHECK ((lesson_number >= 1) AND (lesson_number <= 30));

-- 2. Novas Lições de Responsabilidade (Noites 7 a 10 - Novo Testamento)
INSERT INTO "public"."dev_lessons" ("id", "theme_id", "theme_name", "development_mode", "age_group", "lesson_number", "title", "biblical_reference", "biblical_story", "reflection", "challenge", "final_message", "share_summary", "created_at") VALUES
('a8bf574c-d9da-4e23-b7fe-6281e98d9b79', 'responsabilidade', 'Responsabilidade', 'personal', 'adulto', 7, 'Fidelidade e Diligência nos Talentos', 'Mateus 25:14-29', 'Jesus ensinou sobre o Reino através da parábola de um senhor que, ao viajar para terras distantes, confiou seus bens aos servos. A um concedeu cinco talentos, a outro dois, e ao último apenas um, segundo a capacidade individual de cada um. Os dois primeiros negociaram prontamente e duplicaram os recursos recebidos. O terceiro servo, dominado pelo medo e pela negligência, cavou a terra e escondeu a prata do seu senhor. Ao retornar para o acerto de contas, o senhor honrou com alegria os servos diligentes, convidando-os a participar da sua celebração e confiando-lhes maiores responsabilidades. Contudo, ao ouvir as desculpas acusatórias daquele que nada produziu, o senhor repreendeu severamente sua preguiça, retirou-lhe o talento não utilizado e o entregou ao que tinha dez, expulsando o servo inútil para a escuridão.', 'A fidelidade a Deus manifesta-se no autogoverno e na gestão diligente das capacidades, do tempo e dos recursos postos em nossas mãos. O servo negligente foi condenado não por ter recebido pouco, mas por paralisar diante do dever e tentar justificar sua inércia culpando o senhor. Deus não tolera desculpas para a omissão espiritual ou prática. Administrar com integridade exige coragem de agir, produzir resultados justos e assumir plenamente o peso das nossas responsabilidades, sabendo que cada dádiva recebida exigirá uma prestação de contas inescapável perante o Criador.', 'Identifique uma tarefa pendente hoje e execute-a com total diligência e sem desculpas.', 'A verdadeira fidelidade transforma recursos confiados em frutos eternos para Deus.', 'Na parábola dos talentos, Jesus ensina que fomos chamados à diligência constante.
Deus confia recursos a cada um e espera ação responsável, não desculpas ou inércia.
A verdadeira mordomia cristã exige autogoverno e dedicação prática no dia a dia.
Prestar contas com integridade é o chamado inegociável de todo servo fiel.', NOW()),
('a1ffab8e-4ca4-459c-8993-561c6001587d', 'responsabilidade', 'Responsabilidade', 'kids', 'kids', 7, 'O Tesouro que Deus Confiou', 'Mateus 25:14-29', 'Jesus contou uma linda parábola sobre um senhor que viajou e confiou moedas valiosas aos seus três servos. Ao primeiro deu cinco moedas, ao segundo deu duas, e ao terceiro deu uma, conforme a capacidade de cada um. Os dois primeiros servos trabalharam com alegria e dedicação, fazendo suas moedas renderem o dobro, como sementes que brotam e dão belos frutos no jardim. Mas o terceiro servo teve medo e preguiça. Ele cavou um buraco na terra e escondeu sua moeda. Quando o senhor voltou, alegrou-se muito com os servos fiéis e lhes deu grandes responsabilidades. Porém, repreendeu o servo que não cuidou do tesouro recebido e apresentou apenas desculpas. Jesus ensina que Deus nos dá dons preciosos para cuidarmos com amor e dedicação.', 'Deus nos entrega pequenos tesouros todos os dias, como uma plantinha que precisa de rega, nossos brinquedos para cuidar e o carinho para repartir com a família. Quando somos fiéis nas pequenas tarefas diárias, mostramos amor a Deus sem inventar desculpas. Ele não espera que façamos coisas impossíveis, mas que cuidemos com todo o coração daquilo que Ele colocou em nossas mãos. Cuidar bem do que recebemos traz alegria ao Pai Celeste.', 'Arrume seus brinquedos com alegria e cuide bem de uma tarefa da sua casa.', 'Cuidar com amor do que Deus nos dá alegra o coração Dele.', 'Na parábola dos talentos em Mateus 25, Jesus ensina a importância de cuidar com fidelidade do que Deus nos confia.
Como sementes bem regadas no jardim, nossos dons devem crescer com dedicação e trabalho alegre.
Ser responsável nas pequenas coisas agrada ao Senhor e enche nossa casa de bênçãos.', NOW()),
('38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'responsabilidade', 'Responsabilidade', 'kids', 'teens', 7, 'Fidelidade e Diligência nos Talentos', 'Mateus 25:14-29', 'Jesus contou a parábola de um homem que, partindo para uma terra distante, chamou seus servos e confiou-lhes seus bens. A um entregou cinco talentos, a outro dois, e a outro um, segundo a capacidade de cada um. O que recebeu cinco talentos negociou com eles e lucrou outros cinco. Da mesma forma, o que recebeu dois ganhou outros dois. Porém, o servo que recebeu um talento cavou a terra e escondeu o dinheiro do seu senhor. Depois de muito tempo, o senhor voltou para ajustar contas. Ele elogiou os dois primeiros servos pela fidelidade e dedicação, confiando-lhes mais responsabilidades. Contudo, ao ouvir as desculpas do terceiro servo, que por medo enterrou o talento recebido, o senhor o repreendeu duramente por sua negligência e mandou tirar-lhe o talento.', 'Deus entrega a cada um de nós dons, tempo, inteligência e oportunidades para serem bem administrados. Na escola, nas tarefas domésticas e nos relacionamentos, a preguiça e as desculpas paralisam nosso crescimento. Ter responsabilidade significa agir com dedicação constante, mesmo quando ninguém está olhando ou quando uma tarefa parece difícil. O Senhor não espera perfeição imediata, mas sim diligência e fidelidade naquilo que já temos em mãos. Quem administra com seriedade os pequenos deveres diários estará preparado para assumir desafios ainda maiores.', 'Realize hoje sua tarefa escolar ou doméstica mais adiada com total dedicação e sem reclamar.', 'A fidelidade no pouco prepara o caminho para receber muito mais de Deus.', 'Na Parábola dos Talentos (Mt 25:14-29), Jesus ensina que devemos multiplicar o que Deus nos confiou.
A negligência e as desculpas geram perdas, enquanto a dedicação diária gera frutos.
Seja fiel hoje nas pequenas tarefas da escola e de casa para honrar a Deus.', NOW()),
('69c94ef8-3555-4f68-bcff-5b8350f5a662', 'responsabilidade', 'Responsabilidade', 'kids', 'young_adults', 7, 'A Diligência que Deus Recompensa', 'Mateus 25:14-29', 'Jesus contou que um homem, ao viajar para longe, chamou seus servos e confiou-lhes seus bens segundo a capacidade de cada um. A um entregou cinco talentos, a outro dois, e a outro um. O primeiro negociou com zelo e conquistou outros cinco. O segundo também dobrou o que recebera. O terceiro, porém, cavou a terra e escondeu a moeda do seu senhor. Ao retornar para o acerto de contas, o senhor elogiou os dois primeiros servos como bons e fiéis, confiando-lhes maiores responsabilidades. Mas o servo negligente apresentou desculpas, acusando a exigência do mestre para justificar a própria inércia. O senhor o repreendeu duramente pela preguiça, tirou-lhe o talento e o entregou ao que tinha dez. Aquele que demonstra diligência com o pouco recebe muito mais, mas o negligente perde até o que pensa possuir.', 'Deus não distribui dons, tempo e recursos para serem guardados na comodidade ou desperdiçados em desculpas. A maturidade cristã exige esforço deliberado e disciplina prática com aquilo que já temos nas mãos, seja nos estudos, no quarto ou nas escolhas feitas longe dos olhos públicos. Apresentar justificativas para a negligência revela um coração descompromissado com a verdade de Deus. A prestação de contas é certa e inevitável. Quem demonstra fidelidade no dever cotidiano pequeno prova que está preparado para assumir responsabilidades muito maiores no futuro.', 'Organize e conclua hoje uma tarefa importante que você vinha adiando por preguiça.', 'A fidelidade no pouco constrói a honra para receber muito.', 'Na Parábola dos Talentos (Mateus 25), Jesus ensina que fomos chamados para agir com zelo e fidelidade sobre o que recebemos de Deus.
A negligência e as desculpas trazem prejuízo, enquanto a diligência no dever diário gera fruto e honra.
Que nossa família viva com disciplina e integridade em cada escolha diária.', NOW()),
('1278750b-d391-49fb-ad90-704ad9414304', 'responsabilidade', 'Responsabilidade', 'personal', 'adulto', 8, 'A Seriedade da Mordomia Fiel', 'Lucas 12:42-48', 'Jesus apresentou aos Seus discípulos a parábola do administrador a quem o senhor encarregou de cuidar dos servos e distribuir o sustento no tempo devido. Bem-aventurado é aquele servo a quem o senhor, quando vier, encontrar trabalhando fielmente; em verdade, ele será colocado sobre todos os bens da casa. Contudo, se aquele homem pensar que o seu senhor demora e começar a espancar os servos e servas, comendo e embriagando-se, o senhor retornará em um dia inesperado e em hora desconhecida. Ele o punirá severamente, destinando-lhe a sorte dos infiéis. O servo que conhecia a vontade de seu senhor e não se preparou, nem agiu conforme essa vontade, receberá muitos açoites. Mas aquele que não a conhecia e fez coisas dignas de castigo, receberá poucos. A quem muito foi dado, muito será exigido; e a quem muito foi confiado, muito mais será pedido.', 'A verdadeira integridade se manifesta no modo como administramos o que nos foi confiado quando ninguém está olhando. Cada recurso, dom, tempo e responsabilidade recebidos representam uma prestação de contas diante de Deus. O descuido com nossos deveres cotidianos nasce da falsa ilusão de impunidade e do esquecimento da autoridade divina. Viver com sobriedade e vigilância exige autogoverno constante e serviço diligente àqueles sob nossos cuidados. A medida de nosso privilégio estabelece o peso de nossa responsabilidade; portanto, sejamos administradores dignos da confiança que o Senhor depositou em nossas mãos todos os dias.', 'Cumpra hoje com excelência uma tarefa negligenciada, honrando sua responsabilidade diante de Deus.', 'A integridade no pouco prepara a alma para o muito de Deus.', 'Em Lucas 12, Jesus ensina sobre a responsabilidade do administrador fiel que cumpre seus deveres com integridade. A quem muito foi confiado, muito mais será exigido na prestação de contas. Que hoje possamos viver com vigilância, autogoverno e diligência diante de Deus.', NOW()),
('a34d02ce-8726-4843-8247-3e6f31b75ab7', 'responsabilidade', 'Responsabilidade', 'kids', 'kids', 8, 'Cuidando Bem do Jardim de Deus', 'Lucas 12:42-48', 'Jesus contou uma parábola sobre um ajudante encarregado de cuidar da casa e alimentar a todos com carinho enquanto o seu senhor viajava. Jesus perguntou: quem é o servo prudente e fiel? É aquele que faz o seu trabalho com amor, mesmo quando ninguém está vigiando. Quando o senhor regressa e encontra a casa arrumada e todos alimentados, ele se alegra e confia tesouros ainda maiores a esse bom amigo. Mas aquele que se torna preguiçoso, briga com os outros e esquece seus deveres recebe uma justa correção. Jesus ensinou que a quem muito foi dado, muito será pedido. Assim como um pequeno pássaro cuida com zelo do seu ninho todos os dias, nós somos chamados a cuidar com dedicação de tudo o que Deus nos entrega.', 'Deus nos deu presentes lindos, como a família, os brinquedos e a nossa casa. Assim como as formiguinhas trabalham juntas cuidando de cada folhinha com paciência, nós também precisamos cuidar das nossas coisas e tarefas diárias. Ser responsável significa fazer o que é certo mesmo quando a mamãe ou o papai não estão olhando. Quando arrumamos nossos brinquedos e tratamos os outros com bondade, mostramos que somos amigos fiéis de Jesus, prontos para guardar com amor tudo o que Ele nos confiou.', 'Guardar todos os seus brinquedos com alegria antes de ir dormir hoje.', 'Quem cuida do pouco com amor recebe muito mais de Deus.', 'Noite 8: O Mordomo Fiel e Prudente (Lucas 12:42-48)
Jesus ensina que ser responsável é cuidar com zelo de tudo o que recebemos, mesmo quando ninguém está olhando.
Assim como os passarinhos cuidam com amor do ninho, somos chamados a cuidar dos nossos deveres diários.
A quem muito é confiado, muito amor e dedicação são esperados!', NOW()),
('3b668d23-afb2-4535-b553-2666e511d9ff', 'responsabilidade', 'Responsabilidade', 'kids', 'teens', 8, 'Fidelidade em Cada Tarefa Diária', 'Lucas 12:42-48', 'Jesus ensinou Seus discípulos usando a parábola do administrador da casa. O senhor encarregou um servo prudente de cuidar de toda a sua propriedade e distribuir o sustento aos outros no tempo certo. Feliz seria aquele homem se o seu senhor voltasse e o encontrasse ocupado com o seu trabalho; ele certamente receberia autoridade sobre todos os bens. Porém, se aquele servo pensasse que o patrão demoraria e começasse a maltratar os outros, a comer e a se embriagar, o senhor voltaria em um dia inesperado. A punição para essa negligência seria severa. Jesus concluiu com uma verdade solene: a quem muito foi dado, muito mais será cobrado; e a quem muito foi confiado, ainda mais será exigido. A integridade exige constância diária, mesmo quando ninguém parece estar vigiando.', 'Você já recebeu recursos valiosos de Deus: tempo, inteligência, acesso aos estudos e a confiança de sua família. Responsabilidade bíblica não é apenas fazer o certo quando os pais ou professores estão olhando, mas manter o compromisso com a verdade em segredo. Quando a preguiça tenta adiar as tarefas escolares ou quando a pressão dos amigos incentiva o desrespeito, lembre-se de que Deus confiou muito a você. A fidelidade nas pequenas decisões diárias constrói um caráter sólido e honra a Deus.', 'Cumpra hoje sua obrigação escolar ou doméstica mais difícil sem ninguém precisar cobrar.', 'Quem é fiel nas pequenas coisas recebe a confiança para coisas maiores.', 'Jesus nos ensina em Lucas 12 que quanto mais recebemos, maior é a nossa responsabilidade diante de Deus.
O servo prudente cumpre seus deveres com dedicação constante, mesmo longe dos olhos do seu senhor.
Em casa e na escola, sejamos fiéis e íntegros nas tarefas diárias para honrar a Cristo.', NOW()),
('6da16cbc-f460-415d-bbec-3b6b4affadd4', 'responsabilidade', 'Responsabilidade', 'kids', 'young_adults', 8, 'Fidelidade Oculta e Grande Responsabilidade', 'Lucas 12:42-48', 'Jesus ensinou aos Seus discípulos a parábola do administrador fiel e prudente, a quem o senhor encarregou de cuidar dos servos e distribuir o alimento no tempo devido. Bem-aventurado seria o servo que, ao retornar de surpresa seu senhor, fosse achado cumprindo com zelo a sua tarefa; a esse, o senhor confiaria todos os seus bens. Porém, se aquele homem pensasse que o senhor tardaria a voltar e começasse a espancar os servos, a comer e a embriagar-se, seria surpreendido em dia e hora inesperados, recebendo severa punição. Jesus advertiu com clareza: aquele que conhece a vontade do seu senhor e não se prepara, nem age conforme essa vontade, receberá muitos açoites. Mas aquele que não a conhece e pratica coisas dignas de castigo, receberá poucos. A quem muito foi dado, muito será exigido; e a quem muito foi confiado, muito mais se pedirá.', 'A verdadeira integridade se manifesta quando ninguém está nos observando. A juventude é o período de administrar privilégios, instrução e talentos recebidos de Deus e da família. Pensar que a prestação de contas está longe produz negligência e relaxamento moral nas escolhas privadas. No entanto, o Senhor nos chama à disciplina diária e à vigilância constante. Quanto maior o entendimento e a oportunidade que você possui, maior é a cobrança de Deus sobre suas atitudes. Viver com responsabilidade significa agir com retidão hoje, honrando a confiança divina em cada pequena decisão.', 'Cumpra hoje uma obrigação pendente em segredo, com excelência e sem reclamar.', 'Nossas escolhas em secreto revelam a nossa fidelidade diante de Deus.', 'Na parábola de Lucas 12:42-48, Jesus nos ensina que a quem muito é confiado, muito mais será cobrado. A verdadeira maturidade cristã exige vigilância, retidão nas escolhas secretas e disciplina diária. Sejamos servos prudentes e fiéis diante do Senhor em todo tempo.', NOW()),
('9b0242c0-605b-46cd-a49f-d552ff629998', 'responsabilidade', 'Responsabilidade', 'personal', 'adulto', 9, 'A Nobreza do Trabalho Fiel', '2 Tessalonicenses 3:6-13', 'Ao escrever à igreja em Tessalônica, o apóstolo Paulo confrontou uma conduta desordenada que enfraquecia a comunidade. Alguns crentes haviam abandonado suas ocupações diárias, vivendo na ociosidade e se intrometendo nos assuntos alheios, enquanto dependiam do sustento de outros irmãos. Paulo lembrou o padrão que ele e seus companheiros estabeleceram: trabalharam com fadiga e esforço, dia e noite, para não serem pesados a ninguém, tornando-se modelo a ser imitado. Com autoridade apostólica, determinou que aquele que não quisesse trabalhar também não deveria comer. Ele exortou esses indivíduos a buscarem a tranquilidade, cumprirem seus próprios deveres e garantirem o próprio sustento com dignidade. Por fim, fez um apelo solene a toda a igreja para que ninguém desanimasse na prática contínua do bem, mantendo a honra do testemunho cristão perante o mundo.', 'A fé cristã não legitima a inércia nem a dependência intencional do esforço alheio. O trabalho diligente é uma expressão direta de adoração e autogoverno moral. Quando assumimos com seriedade as nossas responsabilidades e tarefas cotidianas, honramos a Deus e protegemos o nosso coração de distrações inúteis e murmurações. A dignidade de comer o fruto do próprio labor fortalece o caráter e gera os recursos necessários para socorrer os verdadeiramente necessitados. Cumprir o dever com fidelidade diária é um ato indispensável de perseverança no bem.', 'Conclua hoje uma tarefa pendente sem transferir obrigações ou buscar atalhos desonestos.', 'O trabalho diligente e honesto honra a Deus e edifica o caráter.', 'Em 2 Tessalonicenses 3, Paulo ensina que a fé se manifesta no trabalho diligente e no cumprimento do próprio dever, rejeitando a ociosidade.
A integridade cristã exige assumir a responsabilidade pelo próprio sustento e persistir sem desanimar na prática contínua do bem.', NOW()),
('002f3307-7176-4f12-a7f0-62c3bb64633b', 'responsabilidade', 'Responsabilidade', 'kids', 'kids', 9, 'Mãozinhas Ocupadas Fazem o Bem', '2 Tessalonicenses 3:6-13', 'O apóstolo Paulo escreveu uma carta cheia de carinho aos cristãos da cidade de Tessalônica. Ele lembrou a todos que, quando esteve com eles, trabalhou com afinco fazendo tendas para não ser um peso para ninguém. Paulo notou que algumas pessoas estavam de braços cruzados, esperando que os outros fizessem tudo em seu lugar. Ele ensinou que o trabalho diário é uma bênção de Deus, assim como as pequenas formigas que cuidam do formigueiro com dedicação. Paulo incentivou cada irmão a cuidar das suas próprias tarefas com capricho e a comer o seu próprio alimento com gratidão. Ele terminou sua mensagem com um conselho precioso: nunca se cansem de fazer o bem. Quem cumpre seus deveres com amor alegra o coração do Senhor e ajuda todos a viverem em perfeita harmonia.', 'Deus criou cada criaturinha com uma missão especial: as abelhas produzem o doce mel e os passarinhos constroem ninhos seguros. Quando você arruma sua cama, guarda seus brinquedos ou ajuda a recolher os pratos, você mostra que é responsável e traz alegria para a família. Fazer a sua parte com carinho e sem resmungar enche a casa de paz. Nunca desanime de ajudar e praticar o bem, pois até as menores mãozinhas podem realizar grandes bênçãos quando trabalham com amor.', 'Guarde seus brinquedos hoje com alegria e sem ninguém precisar pedir.', 'Mãos que trabalham com amor espalham a bondade de Deus pelo mundo.', 'Paulo ensinou em Tessalônica o valor de cumprir as próprias tarefas e não depender do cansaço alheio. Assim como na natureza cada criatura faz sua parte, nós somos chamados a cuidar de nossos deveres com alegria. Nunca se canse de fazer o bem e abençoar seu lar com atitudes prestativas!', NOW()),
('36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'responsabilidade', 'Responsabilidade', 'kids', 'teens', 9, 'A Nobreza do Próprio Esforço', '2 Tessalonicenses 3:6-13', 'O apóstolo Paulo escreveu à igreja de Tessalônica com uma instrução enérgica sobre disciplina e trabalho. Alguns membros daquela comunidade haviam abandonado suas ocupações cotidianas, vivendo de forma desordenada e dependendo do sustento alheio enquanto se intrometiam nos assuntos dos outros. Paulo lembrou a todos o exemplo que ele mesmo deixou: trabalhou dia e noite com as próprias mãos para não ser pesado a ninguém. O apóstolo estabeleceu uma regra clara de convivência: quem não quer trabalhar também não deve comer. Ele exortou os irmãos a manterem a rotina com serenidade, ganhando o próprio pão com dignidade e honrando a Deus em seus deveres. Por fim, deixou uma ordem definitiva para toda a comunidade cristã: jamais se cansar de praticar o bem.', 'Esperar que os pais façam seus trabalhos escolares, deixem seu quarto arrumado ou assumam suas obrigações diárias é fugir da responsabilidade. Deus nos chama para a maturidade e para a iniciativa própria. Quando você estuda com dedicação, cuida de suas coisas e ajuda em casa sem precisar de cobranças constantes, você demonstra caráter cristão e respeito por sua família. O esforço honesto traz paz à consciência e constrói uma vida útil. Assuma o compromisso de fazer a sua parte todos os dias, pois a fidelidade nas pequenas tarefas diárias prepara você para grandes responsabilidades no futuro.', 'Realize hoje uma tarefa de casa ou escolar antes que alguém precise pedir.', 'Assumir o próprio esforço constrói caráter e honra a Deus diariamente.', 'Na Noite 9, aprendemos com 2 Tessalonicenses 3:6-13 que o trabalho honesto e a iniciativa própria honram a Deus. Paulo nos ensina a não depender do esforço alheio, mas a cumprir nossos deveres com dedicação diária. Assuma suas tarefas com maturidade e jamais se canse de fazer o bem.', NOW()),
('c459abdf-6f14-4b5f-bf29-523cd81403e9', 'responsabilidade', 'Responsabilidade', 'kids', 'young_adults', 9, 'A Honra do Próprio Esforço', '2 Tessalonicenses 3:6-13', 'O apóstolo Paulo escreveu à igreja de Tessalônica com uma exortação firme sobre a conduta diária dos crentes. Alguns membros da comunidade viviam de forma desordenada, recusando-se a trabalhar e intrometendo-se na vida alheia, dependendo injustamente do sustento dos outros. Paulo lembrou a todos do exemplo prático que ele e seus companheiros deram enquanto estiveram entre eles. Dia e noite, eles trabalharam com esforço e fadiga na fabricação de tendas para não serem pesados a ninguém, mesmo tendo o direito ao sustento ministerial. Paulo estabeleceu uma ordem direta: quem não quer trabalhar, também não deve comer. Por fim, exortou os irmãos a manterem a disciplina diária, a comerem o próprio pão fruto do seu trabalho e a jamais desanimarem de praticar o bem.', 'A maturidade cristã exige rejeitar a preguiça e assumir a responsabilidade pelo cumprimento fiel dos próprios deveres. Depender desnecessariamente dos outros ou transferir tarefas pessoais enfraquece o caráter e gera desordem. O trabalho honesto, seja nos estudos ou nas tarefas de casa, honra a Deus e constrói a disciplina indispensável para o futuro. Quando você realiza suas obrigações com dedicação e iniciativa própria, desenvolve firmeza moral e testemunha a fé por meio de atitudes produtivas.', 'Conclua hoje uma tarefa pendente sem que ninguém precise pedir ou lembrar você.', 'A disciplina no trabalho diário constrói um caráter aprovado por Deus.', 'Noite 9: A Honra do Próprio Esforço. Paulo ensinou aos tessalonicenses que a fé exige disciplina, responsabilidade e trabalho honesto. A verdadeira maturidade se manifesta quando cumprimos nossas obrigações diárias com diligência e nunca nos cansamos de fazer o bem.', NOW()),
('f0cbf542-a5a3-4519-a1ed-76f10984b76a', 'responsabilidade', 'Responsabilidade', 'personal', 'adulto', 10, 'O Padrão da Autoliderança Cristã', '1 Timóteo 4:12-16', 'O apóstolo Paulo escreveu ao jovem Timóteo com instruções firmes sobre a responsabilidade de sua vocação em Éfeso. Consciente dos desafios pastorais, Paulo exortou Timóteo a não permitir que ninguém desprezasse a sua mocidade, mas a se tornar o próprio modelo para os fiéis. Esse padrão deveria se manifestar visivelmente na palavra, no procedimento, no amor, na fé e na pureza moral. Paulo recomendou dedicação contínua à leitura pública das Escrituras, à exortação e ao ensino, sem negligenciar o dom concedido pela imposição de mãos. A ordem apostólica culminou em um chamado solene: atentar cuidadosamente para si mesmo e para a doutrina, perseverando nessas práticas espirituais. Somente através desse rigoroso autogoverno e vigilância pessoal, Timóteo seria capaz de salvar tanto a si mesmo quanto àqueles que ouviam atentamente as suas instruções.', 'A verdadeira liderança espiritual começa com o governo vigilante do próprio coração. Antes de corrigir ou guiar outras pessoas, você é chamado a examinar seu proceder diário, alinhando palavras e atitudes com a verdade bíblica. A maturidade cristã não tolera a hipocrisia de ensinar o que não se vive. Quando você cuida de si mesmo, cultivando pureza, amor genuíno e perseverança na doutrina, sua conduta silenciosa torna-se um testemunho poderoso de fé. Seja o exemplo vivo que inspira fidelidade e reflete o caráter imutável de Cristo no mundo.', 'Avalie suas palavras e atitudes hoje, corrigindo imediatamente qualquer desalinhamento com a verdade bíblica.', 'A autoridade do seu testemunho nasce do rigor da sua autoliderança.', 'Paulo exortou Timóteo a ser exemplo dos fiéis na palavra, na conduta, no amor, na fé e na pureza (1 Tm 4:12-16). A verdadeira liderança começa quando cuidamos de nossa própria integridade diante de Deus. Cultive o autogoverno e deixe que sua vida seja um testemunho diário da verdade de Cristo.', NOW()),
('b6de0ee0-9505-41a6-b8c3-039c38224805', 'responsabilidade', 'Responsabilidade', 'kids', 'kids', 10, 'Uma pequena luz que brilha forte', '1 Timóteo 4:12-16', 'O apóstolo Paulo escreveu uma carta cheia de carinho para o jovem Timóteo. Muitas pessoas podiam pensar que Timóteo era jovem demais para liderar e ensinar na igreja, mas Paulo o encorajou a não ter medo. Ele disse que mesmo sendo jovem, Timóteo deveria ser um exemplo vivo para todos ao seu redor. Paulo ensinou que o jovem líder precisava cuidar bem de suas palavras, de suas atitudes diárias, do seu amor sincero, de sua fé firme e de seu coração puro. Timóteo foi orientado a se dedicar com alegria à leitura da Palavra de Deus, ao ensino e ao dom especial que havia recebido do Senhor. Cuidando da sua própria conduta e perseverando na verdade, Timóteo ajudaria a si mesmo e a todas as pessoas que o ouviam com atenção.', 'Assim como um pequeno vaga-lume ilumina a noite escura na floresta com seu brilho suave, você não precisa esperar crescer para ser um exemplo bom em sua casa. Quando você escolhe falar palavras doces, guardar seus brinquedos com alegria e demonstrar carinho pelos seus pais, sua vida reflete a luz de Jesus. Cuidar do que falamos e fazemos é nossa responsabilidade diária. Deus se alegra muito quando um coração infantil decide amar, confiar e obedecer com pureza e bondade.', 'Fale palavras gentis hoje e ajude seus pais com um sorriso no rosto.', 'Mesmo sendo pequeno, seu bom exemplo ilumina a vida de todos.', 'Na carta a Timóteo, Paulo ensina que a idade não impede ninguém de ser exemplo de fé e pureza.
Assim como pequenas luzes na floresta, nossas crianças podem iluminar o mundo com palavras e atitudes boas.
Cuidar da própria conduta com responsabilidade e alegria enche o lar da presença de Deus.', NOW()),
('6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'responsabilidade', 'Responsabilidade', 'kids', 'teens', 10, 'Seja Exemplo em Toda Conduta', '1 Timóteo 4:12-16', 'Paulo escreveu uma carta fundamental ao jovem Timóteo, que liderava a igreja em Éfeso enfrentando muitas pressões. O apóstolo o instruiu firmemente a não deixar que ninguém o desprezasse por causa da sua pouca idade. Em vez de exigir respeito com palavras vazias, Timóteo deveria conquistar a confiança de todos tornando-se um exemplo vivo no falar, no procedimento diário, no amor genuíno, na firmeza da fé e na pureza de coração. Paulo ordenou que ele se dedicasse com zelo à leitura pública das Escrituras Sagradas, ao ensino bíblico e à oração, sem negligenciar o dom espiritual recebido diante da comunidade. O jovem líder precisava vigiar constantemente seus próprios passos e a sã doutrina bíblica, perseverando nesses princípios diários. Assim, cuidando de sua conduta e testemunho, Timóteo preservaria tanto a sua própria caminhada quanto a vida das pessoas que o ouviam com atenção.', 'Muitos jovens acreditam que a maturidade depende da idade, mas a Bíblia ensina que ela se revela pelo caráter e pela responsabilidade. Na escola ou entre amigos, a pressão para falar mal dos outros, trapacear ou agir com grosseria é real. Assumir a responsabilidade por seus atos exige autodomínio. Quando você escolhe a honestidade, responde com respeito e protege a pureza de suas decisões, sua vida fala mais alto que qualquer discurso. Ser exemplo não significa buscar aplausos, mas honrar a Deus onde quer que você esteja, influenciando os outros para o bem.', 'Pratique hoje uma atitude de respeito e honestidade, sem esperar que alguém peça.', 'Sua conduta diária é o testemunho mais claro da sua fé.', 'Em 1 Timóteo 4:12-16, Paulo ensina que a juventude não impede ninguém de liderar pelo exemplo no falar, no amor e na pureza.
Nossa conduta diante dos amigos e familiares deve demonstrar a fé de modo prático.
Hoje aprendemos a assumir a responsabilidade de viver com integridade e sabedoria em qualquer ambiente.', NOW()),
('74449d35-3442-4dae-a540-80b7cb84bd0a', 'responsabilidade', 'Responsabilidade', 'kids', 'young_adults', 10, 'Seja Exemplo em Toda Conduta', '1 Timóteo 4:12-16', 'O apóstolo Paulo escreveu ao jovem Timóteo enquanto este liderava a exigente igreja em Éfeso. Diante de desafios complexos e da desconfiança de alguns quanto à sua pouca idade, a instrução apostólica foi contundente: ninguém deveria desprezar a sua mocidade. Em vez de exigir respeito por imposição, Timóteo foi ordenado a tornar-se o padrão dos fiéis na palavra, no procedimento, no amor, na fé e na pureza moral. Paulo instruiu o jovem a dedicar-se integralmente à leitura pública das Escrituras, à exortação e ao ensino da sã doutrina, sem negligenciar o dom concedido por Deus. A responsabilidade pessoal exigia constância, vigilância sobre si mesmo e disciplina rigorosa, para que o seu progresso espiritual fosse evidente a todos. A fidelidade perseverante na conduta e no ensino guardaria tanto a sua própria vida quanto a vida daqueles que o ouviam.', 'A verdadeira maturidade não é medida pelos anos de vida, mas pelo compromisso diário com a retidão e a autodisciplina. Você não precisa esperar a vida adulta chegar para assumir o controle dos seus hábitos, pensamentos e escolhas no ambiente privado. Ser padrão em pureza, fala e atitudes exige coragem para estabelecer limites firmes diante das pressões ao redor. Quando você cuida de sua conduta e honra a Deus em secreto, seu testemunho público ganha autoridade autêntica. A disciplina que você cultiva hoje sustentará seu caráter, seu futuro e sua fidelidade diante de Deus e dos homens.', 'Identifique um hábito secreto para corrigir hoje e alinhar sua conduta à pureza bíblica.', 'A sua fidelidade diária no secreto define o peso do seu testemunho.', 'Paulo instruiu Timóteo a ser exemplo dos fiéis na palavra, no amor, na pureza e na fé, sem permitir que desprezassem sua juventude (1Tm 4:12-16).
A verdadeira maturidade cristã nasce da disciplina pessoal e da vigilância sincera sobre o próprio caráter.
Assuma a responsabilidade de viver como padrão de integridade hoje mesmo!', NOW());

INSERT INTO "public"."dev_questions" ("id", "lesson_id", "question_text", "display_order") VALUES
('5581429d-9542-401a-9b6b-7ce89e205388', 'a8bf574c-d9da-4e23-b7fe-6281e98d9b79', 'Qual foi o critério do senhor para distribuir os talentos e por que o terceiro servo foi condenado?', 1),
('4e895861-eb0a-4bec-8c38-67478dbff040', 'a8bf574c-d9da-4e23-b7fe-6281e98d9b79', 'Em quais áreas da sua vida você tem sido tentado a esconder seus recursos por receio ou comodismo?', 2),
('4570ab22-6af0-45bb-b9c1-8ad1a4832577', 'a8bf574c-d9da-4e23-b7fe-6281e98d9b79', 'Que ação concreta você tomará nesta semana para multiplicar diligentemente o que Deus colocou em suas mãos?', 3),
('95a7dc58-c1bb-4f81-a185-023501ae466e', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'O que os dois servos fiéis fizeram com as moedas que receberam do senhor?', 1),
('7da359ec-75ad-4048-9439-587e4fd2a27e', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'Que coisas boas e dons Deus entregou para você cuidar na sua casa hoje?', 2),
('63805995-4b0e-45b9-b4d5-c81dd49644d2', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'O que você pode fazer hoje com dedicação e sem reclamar para ajudar sua família?', 3),
('3e3c4c91-89ab-45bf-8215-3f9e29bcbc61', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'Por que o senhor repreendeu o servo que recebeu apenas um talento?', 1),
('29146370-48e5-4717-a7c5-776787c112ee', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'Em quais momentos você sente vontade de dar desculpas para adiar uma responsabilidade escolar ou familiar?', 2),
('b2f9457b-4b16-4cab-9f66-1b4fcfd52e3b', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'O que você pode fazer hoje para cuidar com mais diligência do tempo e dos talentos que Deus lhe deu?', 3),
('a0fb76b6-93d1-4a61-8af7-a7d65a68f089', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Por que o senhor repreendeu com tanta severidade o servo que apenas enterrou o talento?', 1),
('cf8a495d-f66f-4d73-8138-04b858533edd', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Em quais tarefas ou escolhas particulares você tem caído na tentação de dar desculpas para a preguiça?', 2),
('aca8ed23-effc-41d0-8994-b4e85cf5fe75', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Qual compromisso prático de disciplina você assumirá esta semana para honrar o que Deus lhe confiou?', 3),
('e1e9665e-faf9-4122-96ce-3222baf47cb7', '1278750b-d391-49fb-ad90-704ad9414304', 'Qual é a principal advertência de Jesus sobre a diferença entre quem conhece a vontade do Senhor e quem a ignora?', 1),
('16f8f7a4-9d55-49d8-aa74-7cfa80cc204a', '1278750b-d391-49fb-ad90-704ad9414304', 'Em quais áreas de sua rotina você tem sido tentado a relaxar o zelo por achar que a prestação de contas está distante?', 2),
('48d7380d-0c50-43f7-bc7a-7550e89a79b6', '1278750b-d391-49fb-ad90-704ad9414304', 'Que ajuste imediato você precisa fazer para administrar com maior fidelidade os recursos e tarefas confiados a você?', 3),
('c0d11883-1e5d-4f4d-9ebf-261b116ae7b7', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'O que o ajudante fiel fazia na casa enquanto o seu senhor estava viajando?', 1),
('a637b350-2b9b-41d8-84c7-efd8e5e4c34c', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'Como você se sente no coração quando faz algo bom sem ninguém precisar mandar?', 2),
('7cf3e4b9-ecc0-4618-85cb-92af4c53e6f4', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'Qual tarefa da nossa casa você vai cuidar com mais capricho a partir de amanhã?', 3),
('558cfe11-9bd5-4838-b510-31c464e2b679', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Qual era a principal diferença de atitude entre o servo prudente e o negligente na parábola?', 1),
('41113d0f-a561-4eb3-9303-0b6b63d2ebce', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Em quais situações do seu dia a dia é mais tentador relaxar no cumprimento das suas obrigações?', 2),
('6005bad0-566d-4e84-9c48-b25de9ed6d52', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Que dever específico você precisa assumir com mais zelo e pontualidade a partir de hoje?', 3),
('bc3164d6-3344-4b49-92ba-b945a7feeffc', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Qual é a principal diferença entre o servo fiel e o servo negligente na parábola de Jesus?', 1),
('5d16ed86-24df-45c9-b53d-10d20873af22', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Em quais áreas da sua vida secreta ou rotina diária é mais difícil manter a disciplina e a vigilância?', 2),
('70c1c587-979f-4709-a811-ca162684040f', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Que dever prático você precisa assumir com mais integridade a partir de hoje?', 3),
('d695e0ce-d745-4a69-8de6-7acc4ea2660a', '9b0242c0-605b-46cd-a49f-d552ff629998', 'Como o exemplo prático de Paulo em Tessalônica corrigiu a conduta dos que viviam na ociosidade?', 1),
('3bbf9140-fe1c-4001-a565-680378d04de9', '9b0242c0-605b-46cd-a49f-d552ff629998', 'Em quais áreas da sua rotina você tem sido tentado a procrastinar ou depender do esforço dos outros?', 2),
('c0dd8e2a-cf83-49c8-89b1-219e595a6dbe', '9b0242c0-605b-46cd-a49f-d552ff629998', 'Que ajuste concreto você fará em seu trabalho para manifestar mais disciplina, integridade e serviço ao próximo?', 3),
('fb612902-b572-473b-a8f7-5427c4a0ce11', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'O que o apóstolo Paulo fazia com as próprias mãos para dar um bom exemplo?', 1),
('82db9d08-8eaa-4611-b978-fed407323658', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'Como você se sente no coração quando termina uma tarefa sozinho e bem feita?', 2),
('b9872088-c104-4568-acf4-c22c5d48b856', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'Qual tarefa da nossa casa você pode fazer hoje com alegria para ajudar a família?', 3),
('d9d3b27d-45f0-4cf0-84b5-723154c7a05a', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Por que o apóstolo Paulo fez questão de trabalhar com as próprias mãos em Tessalônica?', 1),
('77d852b1-6676-4988-be71-3e6e4ef9d481', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Em quais momentos você sente a tentação de deixar que outros façam as suas tarefas?', 2),
('c9f00b5c-0ff0-4c7d-92f5-47ac3fe99ad6', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Qual responsabilidade prática você vai assumir sozinho a partir de hoje?', 3),
('f3dc2c3a-727f-40e0-8eed-0626ef4ce0f7', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Qual exemplo prático o apóstolo Paulo deixou sobre o sustento e o trabalho diário?', 1),
('745d67d7-16dd-4ef6-a8ff-bfd3ebc7ba57', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Em quais tarefas diárias você percebe a tentação de procrastinar ou depender de outros?', 2),
('c75accd6-ee42-4a0d-a455-00f7ac97e59b', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Que iniciativa concreta você assumirá hoje para ser mais proativo em suas responsabilidades?', 3),
('88a356dc-d5a2-4e5e-abb9-603ee797a791', 'f0cbf542-a5a3-4519-a1ed-76f10984b76a', 'De acordo com 1 Timóteo 4:12-16, em quais áreas específicas Timóteo foi instruído a ser modelo para os fiéis?', 1),
('62048b7e-ceba-42c1-8391-665d4aff87e1', 'f0cbf542-a5a3-4519-a1ed-76f10984b76a', 'Em qual aspecto do seu cotidiano (palavras, conduta, amor, fé ou pureza) você reconhece maior necessidade de vigilância pessoal?', 2),
('4031ddff-61a6-4658-83d5-2b73a0dcbb09', 'f0cbf542-a5a3-4519-a1ed-76f10984b76a', 'Que medida concreta de autogoverno e disciplina você implementará a partir de hoje em sua rotina?', 3),
('af4934d5-a298-4726-895a-fea78b01ff46', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'O que o apóstolo Paulo pediu para Timóteo ser, mesmo sendo jovem?', 1),
('ee66aad3-42bd-4ca7-8ec0-d97c04b9e486', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'Como você se sente quando suas palavras e atitudes trazem alegria para a nossa família?', 2),
('3882faae-a456-462d-bbcf-496275558104', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'Qual atitude cheia de amor você pode ter hoje para ser um bom exemplo?', 3),
('180bc175-627d-4dfb-9de5-73cd17438b29', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Quais foram as áreas específicas em que Paulo orientou Timóteo a ser padrão para todos?', 1),
('b50c5173-7f16-473a-b060-7c432f4e20f9', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Em quais momentos na escola ou com amigos você sente mais dificuldade em manter uma conduta correta?', 2),
('080357db-c708-417c-af9f-200876610f77', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Qual mudança simples na sua fala ou comportamento você pode aplicar amanhã para ser um bom exemplo?', 3),
('e072397a-4cdf-4e53-bce7-7980b9225b73', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'De acordo com as instruções de Paulo a Timóteo, em quais áreas específicas o jovem deveria ser padrão para a igreja?', 1),
('e368df5a-0ea9-47e0-89af-9e74070726ed', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'Quais pressões cotidianas tornam mais difícil manter a pureza e a integridade nas palavras e atitudes quando você está sozinho ou entre amigos?', 2),
('331d44c5-f672-451a-b80a-a3700aec9318', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'Que ajuste concreto você precisa fazer em sua rotina para demonstrar progresso visível em sua disciplina espiritual e moral?', 3);

INSERT INTO "public"."dev_prayers" ("id", "lesson_id", "role", "text_content", "display_order") VALUES
('94b023b1-c133-498c-8ed4-29158397071b', 'a8bf574c-d9da-4e23-b7fe-6281e98d9b79', 'Individual', 'Senhor Deus, reconheço que tudo o que possuo provém da Tua soberana graça. Perdoa a minha negligência e as desculpas que tantas vezes uso para justificar a inércia. Concede-me autogoverno, coragem e integridade para administrar com sabedoria e zelo cada dom, tempo e oportunidade que colocaste em minhas mãos. Que a minha conduta diária seja pautada pelo trabalho diligente e pela fidelidade prática, honrando o Teu santo nome até o dia da nossa prestação de contas. Em nome de Jesus, amém.', 1),
('e01ad784-6e89-49db-a74b-5d0414b67a29', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'Pai', 'Senhor, ajuda-me a ensinar meus filhos a cuidarem com zelo de tudo o que Tu nos confias.', 1),
('fce5df71-19a5-4c08-955b-9151e78ecba3', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'Filho', 'Jesus, obrigado pelos meus dons. Quero usar minhas mãos e meu coração para Te agradar.', 2),
('edb873d6-434f-44c7-a665-57494b0f9442', 'a1ffab8e-4ca4-459c-8993-561c6001587d', 'Juntos', 'Pai Celeste, queremos ser servos fiéis, cuidando com amor de tudo o que nos deste. Amém.', 3),
('d7904ee2-62b6-48bd-a877-38c01315b443', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'Pai', 'Senhor, ajuda-me a ser um exemplo de diligência e integridade no cumprimento dos meus deveres diários.', 1),
('14427513-0edd-43b4-b129-21e1f62d0e64', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'Filho', 'Deus, perdoa minha preguiça e dá-me coragem para usar meus talentos e estudos para a Tua glória.', 2),
('9022e2bf-80cd-43c2-89c2-78af66ebe1fd', '38f5f8c1-9de4-4a44-9eb3-9f516a8edd90', 'Juntos', 'Pai celestial, ensina nossa família a administrar com sabedoria tudo o que nos deste. Amém.', 3),
('0d90fc7d-02e3-47d0-85f9-270480aa9607', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Pai', 'Senhor, capacita-me a ser um exemplo consistente de trabalho, disciplina e integridade moral para o meu filho.', 1),
('6d926f7b-1822-4955-a118-5f506e458dde', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Filho', 'Deus, afasta de mim a preguiça e as desculpas, dando-me firmeza para administrar bem meu tempo e meus deveres.', 2),
('d77247f0-952b-47f3-aa11-62d7c62b0840', '69c94ef8-3555-4f68-bcff-5b8350f5a662', 'Juntos', 'Pai celestial, faz de nossa casa um lugar de honra, fidelidade e prestação de contas sincera diante de Ti. Amém.', 3),
('8395da74-cdad-4264-862e-211b5775f746', '1278750b-d391-49fb-ad90-704ad9414304', 'Individual', 'Senhor Deus, Tu me confiaste dons, tempo e pessoas para cuidar com retidão. Perdoa-me pelos momentos em que negligenciei meus deveres ou agi com egoísmo, esquecendo que presto contas a Ti. Concede-me um coração vigilante, sóbrio e comprometido com a Tua vontade. Que a minha conduta diária reflita fidelidade inabalável, tanto nas pequenas tarefas quanto nas grandes decisões. Em nome de Jesus, amém.', 1),
('c385600d-4397-4e49-b8c1-30f79ee53b2b', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'Pai', 'Senhor, ensina nosso lar a ter um coração fiel e zeloso em cada pequeno dever diário.', 1),
('222eb4ba-0569-428a-b213-e0440f51b692', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'Filho', 'Jesus, ajuda minhas mãozinhas a cuidarem com carinho dos meus brinquedos e da minha família.', 2),
('9ac89617-c095-431d-a7b6-d465c437c85d', 'a34d02ce-8726-4843-8247-3e6f31b75ab7', 'Juntos', 'Pai do Céu, queremos ser ajudantes bons, atentos e obedientes todos os dias. Amém!', 3),
('cf2a6e81-6eb1-4089-b57c-171d3a0a6070', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Pai', 'Senhor, ajuda-me a liderar minha casa com sabedoria, sendo um exemplo visível de dedicação, integridade e fidelidade aos Teus princípios.', 1),
('500cc264-f66a-4878-9c67-52763a20f194', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Filho', 'Pai celestial, dá-me forças para vencer a preguiça nos estudos e para agir com retidão mesmo quando ninguém estiver me observando.', 2),
('66e9d634-c49f-4ad2-ae81-047009e1672c', '3b668d23-afb2-4535-b553-2666e511d9ff', 'Juntos', 'Senhor Deus, consagramos nosso tempo e nossas tarefas a Ti, buscando sempre cumprir com zelo tudo o que nos confiaste. Amém.', 3),
('4f8db420-25fb-40b6-92ac-c556bd0c9c31', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Pai', 'Senhor, ajuda-me a ser um modelo de vigilância e integridade, guiando meus filhos pelo exemplo e pelo temor a Ti.', 1),
('d5b6aca0-39f2-4fa2-9d52-516b7775aa34', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Filho', 'Pai celestial, concede-me maturidade e disciplina para honrar a confiança recebida, vivendo com retidão mesmo quando ninguém vê.', 2),
('799b63bb-0164-4cb0-bc52-6fdfa5818462', '6da16cbc-f460-415d-bbec-3b6b4affadd4', 'Juntos', 'Senhor, firma nossa casa na Tua verdade e torna-nos servos fiéis até o dia do Teu retorno. Amém.', 3),
('31352869-5920-4c49-828e-34d7a3109260', '9b0242c0-605b-46cd-a49f-d552ff629998', 'Individual', 'Senhor Deus, agradeço pelo dom do trabalho e pela oportunidade de produzir com as minhas próprias mãos. Livra-me da preguiça, do desânimo e da inclinação para a ociosidade. Concede-me integridade e disciplina para cumprir minhas obrigações com excelência e sem murmurar. Que a minha dedicação diária sirva de bom testemunho e me permita abençoar os que realmente precisam. Em nome de Jesus, amém.', 1),
('fc31d3be-314f-486e-b70b-789f04e1286d', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'Pai', 'Senhor, dá-me sabedoria para ensinar meus filhos pelo exemplo de dedicação, paciência e amor no trabalho diário.', 1),
('ae6e5f4b-e3a4-4176-abdf-03de8099deda', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'Filho', 'Jesus, ajuda minhas mãozinhas a cuidarem dos meus brinquedos e a nunca terem preguiça de ajudar.', 2),
('9bebdd02-9d10-4203-9ddf-7a2fb14e0aa1', '002f3307-7176-4f12-a7f0-62c3bb64633b', 'Juntos', 'Papai do Céu, abençoa a nossa família para que trabalhemos juntos em harmonia e nunca nos cansemos de fazer o bem. Amém.', 3),
('f1499402-1e00-4ec5-afb1-cd02c489b596', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Pai', 'Senhor, ajuda-me a ser exemplo de trabalho diligente e a ensinar responsabilidade com sabedoria e amor.', 1),
('25b51cb0-1338-4794-b784-f255dfcc665f', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Filho', 'Deus, dá-me ânimo para cumprir meus deveres sem reclamar e sem depender do esforço dos outros.', 2),
('081c82d7-7708-4429-bb80-b0e228396c28', '36e289e5-6e47-4ad8-bd4b-e6d78fa1da5c', 'Juntos', 'Pai celestial, ensina nossa família a cooperar unida e a nunca se cansar de fazer o bem. Amém.', 3),
('d51539a0-5c88-42b1-9d7a-b6e35a6bc938', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Pai', 'Senhor, ajuda-me a ser exemplo vivo de diligência, honestidade e trabalho digno para minha casa.', 1),
('e59e6f95-c5c1-488b-af33-a90fe6746063', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Filho', 'Deus, afasta de mim a preguiça e ensina-me a cumprir meus deveres com integridade e autonomia.', 2),
('b81e8790-94d3-4046-bf45-b41df9dda0a0', 'c459abdf-6f14-4b5f-bf29-523cd81403e9', 'Juntos', 'Pai Celestial, consagra as obras de nossas mãos e dá-nos perseverança para nunca cansar de fazer o bem. Amém.', 3),
('63e2d04d-e747-4ad7-9c7b-b5bc63a6a61e', 'f0cbf542-a5a3-4519-a1ed-76f10984b76a', 'Individual', 'Senhor Deus, reconheço a responsabilidade que me confiaste de viver como um padrão autêntico de fidelidade. Guarda meus passos, meus lábios e minhas intenções. Dá-me graça e discernimento para cuidar da minha conduta, perseverando na Tua Palavra com integridade e amor sincero. Amém.', 1),
('57f10fe7-0049-42f2-b420-0572012d76ab', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'Pai', 'Senhor Deus, ajuda-me a ser um modelo diário de retidão, paciência e amor para guiar meu filho.', 1),
('ec610992-ef09-4d39-88b7-062f47938b7a', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'Filho', 'Jesus, ajuda meu coração a ser puro e faz as minhas palavras serem sempre doces e carinhosas.', 2),
('9152bb25-8f26-427e-81f2-7662bde999cd', 'b6de0ee0-9505-41a6-b8c3-039c38224805', 'Juntos', 'Pai celestial, que a nossa casa brilhe com a Tua verdade e que nossas atitudes glorifiquem o Teu nome. Amém!', 3),
('c61697c7-cd48-41a0-9010-737ba723710c', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Pai', 'Senhor, capacita-me a liderar meu filho com retidão, sendo o primeiro exemplo de fé, amor e integridade dentro do nosso lar.', 1),
('344767ef-2ea8-418c-8539-877df5e01359', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Filho', 'Deus, dá-me coragem para não ceder à pressão dos outros e guarda meu coração para que minhas palavras e atitudes te agradem.', 2),
('738c93e3-6a6e-4d76-b586-fb4aba749aa1', '6f4e8572-4dc3-4cf1-9f72-0214970f6341', 'Juntos', 'Pai celestial, ensina nossa família a cuidar da conduta diária, honrando o teu nome com vidas puras, obedientes e fiéis. Amém.', 3),
('46112143-cb61-419b-9fcd-8eeb4473a3f4', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'Pai', 'Senhor Deus, peço que fortaleças meu filho para viver com firmeza, honra e discernimento, sendo guardado em pureza e retidão diante de Ti.', 1),
('7c90ec7f-8912-49ce-9360-d4dc788288cc', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'Filho', 'Pai celestial, dá-me coragem e disciplina para guardar meu coração, controlar minhas escolhas e ser um exemplo vivo de fé e integridade.', 2),
('9598a9e8-2f53-46b5-b398-3a95c09cbc33', '74449d35-3442-4dae-a540-80b7cb84bd0a', 'Juntos', 'Senhor, consagramos nossas vidas e nosso lar ao Teu serviço. Que a nossa conduta diária glorifique o Teu santo nome. Amém.', 3);

