-- 1. Atualizar a constraint de número de lições para permitir até 30 lições por tema (caso ainda não tenha sido aplicada)
ALTER TABLE "public"."dev_lessons" 
  DROP CONSTRAINT IF EXISTS "dev_lessons_lesson_number_check",
  ADD CONSTRAINT "dev_lessons_lesson_number_check" CHECK ((lesson_number >= 1) AND (lesson_number <= 30));

-- 2. Novas Lições de Perseverança (Noites 7 a 10 - Novo Testamento)
INSERT INTO "public"."dev_lessons" ("id", "theme_id", "theme_name", "development_mode", "age_group", "lesson_number", "title", "biblical_reference", "biblical_story", "reflection", "challenge", "final_message", "share_summary", "created_at") VALUES
('d62c3014-5880-404f-a37c-88353ae2dc55', 'perseveranca', 'Perseverança', 'personal', 'adulto', 7, 'A Certeza da Colheita Fiel', 'Gálatas 6:9-10', 'Paulo escreve às comunidades da Galácia, onde muitos crentes enfrentavam desgaste e desânimo após conflitos doutrinários e dificuldades cotidianas. O apóstolo utiliza a metáfora da semeadura e da ceifa para renovar o vigor dos fiéis. Ele os exorta com firmeza a não esmorecerem na prática do bem, pois a colheita espiritual possui uma data certa, condicionada à perseverança e à recusa em desistir. Enquanto houver oportunidade nesta vida, o cristão deve agir ativamente em favor de todos os homens, dedicando especial zelo e fidelidade à família da fé. Paulo lembra aos irmãos que o serviço cristão silencioso não é vão diante de Deus, mas uma semente eterna que certamente florescerá no tempo oportuno determinado pela soberania divina.', 'A rotina de fazer o bem muitas vezes é marcada pelo cansaço e pela ausência de resultados imediatos. Quando o retorno parece inexistente, a tentação de desanimar ou agir com negligência se torna real. Contudo, a maturidade cristã exige autogoverno e fidelidade contínua, mesmo sob fadiga. A colheita espiritual não segue o ritmo da nossa pressa, mas o cronograma perfeito de Deus. Perseverar no bem sem recuar é a prova máxima de integridade e confiança no Senhor, que honra cada ato de obediência.', 'Pratique hoje uma boa ação concreta em favor de alguém, sem esperar reconhecimento.', 'Quem persevera na semeadura correta colherá no tempo estabelecido por Deus.', 'Em Gálatas 6:9-10, o apóstolo Paulo nos instrui a não esmorecer na prática do bem, garantindo que colheremos no devido tempo se não desfalecermos.
A perseverança em fazer o bem exige paciência e fidelidade diária.
Aproveite cada oportunidade hoje para abençoar o próximo com integridade.', NOW()),
('45a668ed-ab58-4243-a6a5-f501816e7a0c', 'perseveranca', 'Perseverança', 'kids', 'kids', 7, 'A Sementinha e a Boa Colheita', 'Gálatas 6:9-10', 'O apóstolo Paulo escreveu uma carta aos irmãos da Galácia com um conselho precioso sobre fazer o bem. Ele explicou que nossas ações são como sementes plantadas na terra. Quando ajudamos um amigo, obedecemos aos pais ou compartilhamos um brinquedo, estamos semeando sementes de amor no jardim de Deus. Mas uma plantinha não nasce de repente; ela precisa de água, sol e muita paciência debaixo da terra escura. Paulo ensinou que não devemos nos cansar nem desistir de praticar o bem, mesmo quando ninguém parece notar ou quando a espera parece demorada. No momento exato planejado pelo Senhor, essas sementes brotam, crescem e se transformam em lindos frutos de alegria. Por isso, enquanto tivermos oportunidade, devemos fazer o bem a todas as pessoas, cuidando com carinho especial de toda a família da fé.', 'Às vezes dá vontade de desanimar quando fazemos o que é certo e ninguém agradece, ou quando ser gentil parece difícil. Mas, assim como o pequeno broto trabalha quieto na terra antes de dar uma fruta doce e madura, cada gesto de carinho e obediência que você planta é guardado por Deus. Continuar fazendo o bem sem desistir traz a bênção do Senhor no momento certo. O amor sempre vale a pena.', 'Faça um favor gentil para alguém hoje com um lindo sorriso, sem esperar recompensa.', 'Quem planta bondade com paciência colhe a doce alegria de Deus.', 'Em Gálatas 6:9-10, o apóstolo Paulo ensina que nossas boas ações são sementes preciosas.
Não devemos desanimar de fazer o bem, pois a colheita chega no tempo certo.
Quando perseveramos no amor com paciência, Deus faz a verdadeira alegria florescer.', NOW()),
('b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'perseveranca', 'Perseverança', 'kids', 'teens', 7, 'A Colheita no Tempo Certo', 'Gálatas 6:9-10', 'O apóstolo Paulo escreveu sua carta às igrejas da Galácia para encorajar os cristãos a permanecerem firmes na fé autêntica. Muitas pessoas naquelas comunidades sentiam cansaço por praticar a verdade em um ambiente difícil e hostil. Paulo usou a figura do agricultor que ara a terra, lança as sementes e precisa esperar pacientemente pelas chuvas e pelo crescimento. Ele advertiu os irmãos: não devemos nos cansar de fazer o bem, pois no tempo devido colheremos, se não desistirmos. Enquanto temos oportunidade, devemos agir com bondade e justiça para com todos, especialmente com os irmãos na fé. A perseverança não era uma opção secundária, mas o compromisso diário de confiar que Deus cumpre Suas promessas no tempo estabelecido.', 'Fazer o que é correto na escola, em casa ou entre amigos nem sempre traz recompensa imediata. Muitas vezes dá trabalho ser honesto em uma prova difícil, ajudar um colega isolado ou manter a disciplina nos estudos quando ninguém parece notar. A tentação de desistir surge quando esperamos aplausos rápidos. A promessa bíblica garante que nenhuma atitude reta é desperdiçada diante de Deus. O bem que você planta hoje trará frutos duradouros no momento certo. Persevere com firmeza, mesmo quando o resultado demorar a aparecer.', 'Faça um ato de bondade hoje sem esperar reconhecimento ou retribuição de ninguém.', 'Quem semeia a verdade colhe a fidelidade de Deus no tempo certo.', 'Gálatas 6:9-10 nos ensina que a perseverança gera frutos no tempo de Deus. Fazer o bem exige paciência, como o agricultor que espera a colheita sem desistir. Mesmo quando ninguém aplaude o seu esforço, continue firme na verdade. O que plantamos com fidelidade hoje certamente florescerá amanhã.', NOW()),
('c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'perseveranca', 'Perseverança', 'kids', 'young_adults', 7, 'A Certeza da Colheita Fiel', 'Gálatas 6:9-10', 'O apóstolo Paulo escreveu às igrejas da Galácia com zelo ardente, advertindo os irmãos sobre as leis espirituais que regem a vida cristã. Enquanto enfrentavam oposições e o cansaço do trabalho cotidiano, muitos discípulos sentiam a tentação de afrouxar o compromisso com a verdade. Paulo os exortou enfaticamente a não desistirem de praticar o bem, pois a colheita é infalível no tempo determinado por Deus. Ele usou a metáfora da lavoura para lembrar que nenhum grão semeado em obediência se perde. Assim como o agricultor espera pacientemente a estação dos frutos, os crentes foram chamados a perseverar com disciplina contínua, usando cada oportunidade diária para abençoar a todos, especialmente a família da fé, confiando no galardão do Senhor.', 'A disciplina de fazer o que é correto quando ninguém está olhando define o seu futuro. Na juventude, a pressa por resultados imediatos tenta você a abandonar os limites morais e a santidade. Contudo, a colheita de Deus não segue o imediatismo humano. Cada escolha sincera de pureza, cada renúncia ao pecado e cada ato de perseverança silenciosa estão gerando frutos eternos. Não desanime diante do cansaço ou da zombaria ao seu redor. Mantenha-se firme no dever bíblico diário, pois quem persevera no bem certamente desfrutará do cumprimento das promessas divinas.', 'Pratique hoje uma boa ação em segredo, sem buscar aplauso ou reconhecimento algum.', 'A perseverança na retidão garante a colheita prometida por Deus.', 'Em Gálatas 6:9-10, o apóstolo Paulo nos ensina que a semeadura da obediência gera frutos certos no tempo de Deus. Não podemos desanimar diante das pressões diárias nem afrouxar nossos limites morais. A perseverança na integridade e na prática do bem garante a colheita das bênçãos do Senhor.', NOW()),
('cc338eb5-d5c2-44e6-8180-056d05736cfa', 'perseveranca', 'Perseverança', 'personal', 'adulto', 8, 'O Fruto Maduro da Provação', 'Tiago 1:2-4, 12', 'Tiago, servo de Deus e do Senhor Jesus Cristo, dirigiu sua carta pastoral aos crentes dispersos pelo mundo antigo, homens e mulheres que enfrentavam severas tribulações cotidianas e perseguições por causa do Evangelho. Conhecendo a realidade daqueles discípulos, o apóstolo não ofereceu ilusões nem alívios fáceis, mas uma exortação profunda: que encarassem as provações com espírito de genuína alegria. Ele ensinou que a prova da fé gera a verdadeira perseverança, virtude indispensável para forjar um caráter maduro, íntegro e inabalável diante das tempestades. Tiago insistiu que a constância deve cumprir plenamente o seu propósito, tornando o servo completo em retidão. Por fim, declarou bem-aventurado aquele que suporta a provação com fidelidade, pois, uma vez aprovado no fogo da adversidade, receberá a coroa da vida prometida por Deus.', 'As adversidades não surgem para destruir quem permanece firmado em Deus, mas para purificar as intenções e amadurecer a conduta. Quando enfrentamos contrariedades no trabalho, no lar ou nas relações diárias, o impulso natural é a queixa ou a fuga. Contudo, a maturidade cristã exige autogoverno para enxergar em cada obstáculo uma oportunidade de exercer a fidelidade e consolidar a integridade. A firmeza de caráter não nasce no conforto, mas na recusa lúcida em ceder à desonestidade e ao desânimo durante a prova.', 'Diante de uma dificuldade hoje, responda com paciência e retidão em vez de murmurar.', 'A perseverança sob a provação forja um caráter digno da eternidade.', 'A carta de Tiago ensina que as provações forjam perseverança e integridade espiritual. Em vez de ceder à queixa diante das dificuldades diárias, somos chamados à firmeza e ao autogoverno. Quem suporta a prova com fidelidade alcança a maturidade de caráter prometida por Deus.', NOW()),
('cda58e7a-1883-4972-a7f5-8493b614cf30', 'perseveranca', 'Perseverança', 'kids', 'kids', 8, 'Crescendo Fortes Como Grandes Árvores', 'Tiago 1:2-4, 12', 'Tiago escreveu uma carta cheia de amor aos amigos de Jesus espalhados por muitos lugares. Ele sabia que eles passavam por dias difíceis, ventos fortes e tempestades. Mas Tiago lhes deu um conselho especial: fiquem muito alegres quando passarem por testes difíceis. Ele explicou que, quando a nossa fé passa por momentos duros, ela funciona como uma plantinha na chuva forte. Em vez de quebrar, a raiz desce mais fundo na terra e o caule fica bem grosso e firme. Quem não desiste no meio da tempestade aprende a ter paciência e se torna forte e maduro, sem faltar nada de bom no coração. No final do caminho, Deus promete uma linda coroa de vida para todos que continuam amando o Senhor com firmeza e alegria, mesmo quando o vento sopra forte.', 'Quando enfrentamos uma tarefa difícil, um brinquedo que quebra ou uma dorzinha chata, podemos nos sentir tristes ou bravos. Mas assim como a árvore precisa do vento para criar raízes profundas, esses momentos nos ensinam a ter paciência e coragem. Deus não nos deixa sozinhos na tempestade; Ele usa cada pequeno desafio diário para moldar um coração forte, gentil e obediente. Quando decidimos não desistir e confiamos no cuidado do Pai do Céu, nós crescemos por dentro e nos tornamos pessoas maduras e cheias de amor.', 'Respirar fundo e pedir ajuda a Deus em vez de reclamar ao errar algo.', 'Cada pequeno desafio nos faz crescer firmes no amor de Deus.', 'Na carta de Tiago (Tg 1:2-4, 12), aprendemos que as provações fortalecem as raízes da nossa fé.
Em vez de desanimar diante das dificuldades, Deus nos convida a confiar e perseverar.
Cada desafio enfrentado produz paciência e a promessa da coroa da vida para quem ama ao Senhor.', NOW()),
('98af54c0-81b3-47d2-a965-cf47f1b3c953', 'perseveranca', 'Perseverança', 'kids', 'teens', 8, 'A Força Forjada na Provação', 'Tiago 1:2-4, 12', 'O apóstolo Tiago escreveu sua carta aos primeiros cristãos espalhados por várias regiões do Império Romano. Aqueles homens e mulheres enfrentavam pobreza, injustiças e forte perseguição por causa da fé em Jesus Cristo. Em vez de lamentar ou mandar que fugissem dos problemas, Tiago surpreendeu a todos com uma instrução direta: encarar as provações com verdadeira alegria. Ele ensinou que o teste da fé serve a um propósito maior, gerando perseverança e firmeza de caráter. Quando essa perseverança atinge a plena maturidade, o crente se torna completo, íntegro e preparado para qualquer desafio. Tiago ainda declarou feliz aquele que resiste firme até o fim, pois receberá a coroa da vida prometida por Deus.', 'As dificuldades da rotina, como notas difíceis, cobranças em casa ou a pressão dos colegas, muitas vezes parecem obstáculos pesados. No entanto, a Bíblia ensina que esses testes são oportunidades para exercitar a paciência e a integridade. Fugir das responsabilidades enfraquece o caráter, mas enfrentar cada situação com obediência a Deus desenvolve firmeza e maturidade. Quando você escolhe não desistir diante do estresse diário, sua fé se fortalece e você se torna alguém confiável, pronto para honrar a Cristo em qualquer ambiente.', 'Enfrente a tarefa mais difícil de hoje com dedicação e sem reclamar.', 'A dificuldade de hoje constrói a maturidade que você terá amanhã.', 'Em Tiago 1, aprendemos que as provações não servem para nos derrubar, mas para forjar perseverança e integridade. Quando enfrentamos a pressão do dia a dia com fidelidade a Deus, nosso caráter amadurece. A perseverança nas dificuldades produz uma fé forte e vitoriosa!', NOW()),
('7e35da2c-0ccf-44a6-8aab-2d043de72208', 'perseveranca', 'Perseverança', 'kids', 'young_adults', 8, 'Maturidade Forjada na Provação da Fé', 'Tiago 1:2-4, 12', 'Ao escrever aos cristãos dispersos entre as nações, Tiago sabia que eles enfrentavam perseguições, privações e fortes pressões para abandonar a fé. Em vez de oferecer condolências vazias, o apóstolo convocou a igreja a encarar cada provação com grande alegria. Ele explicou que a prova da fé não visa à destruição, mas produz a perseverança necessária para forjar um caráter maduro, íntegro e sem defeito. Tiago comparou a caminhada cristã a um teste de resistência onde a fidelidade sob pressão gera solidez espiritual. Ele concluiu com uma promessa solene aos que resistem firmes: aquele que suporta a provação com integridade receberá a coroa da vida, prometida pelo Senhor àqueles que O amam de todo o coração, mesmo nas horas mais difíceis da vida.', 'As dificuldades nos estudos, a pressão dos colegas e a tentação de afrouxar os limites morais no secreto não são desculpas para desistir, mas testes que revelam a autenticidade do seu caráter. Quando você escolhe a disciplina e a obediência a Deus diante do desconforto, sua fé ganha raízes profundas. A maturidade espiritual não nasce no conforto, mas na decisão consciente de permanecer fiel mesmo quando ninguém está olhando. Não tema o peso do processo: Deus usa a disciplina de hoje para preparar sua integridade moral de amanhã.', 'Cumpra hoje com disciplina uma tarefa difícil sem reclamar e sem buscar atalhos fáceis.', 'A provação suportada com fidelidade forja um caráter inabalável diante de Deus.', 'Tiago nos ensina que as provações servem para testar e amadurecer nossa fé, gerando perseverança e integridade. Quando enfrentamos dificuldades com fidelidade, somos preparados para o futuro e honrados por Deus. Permaneça firme nas escolhas certas de hoje!', NOW()),
('9a1aaa1c-2584-452e-9c66-b8c56136d551', 'perseveranca', 'Perseverança', 'personal', 'adulto', 9, 'A Fidelidade Guardada até o Fim', '2 Timóteo 4:6-8', 'Nas sombras de uma prisão romana fria e solitária, o apóstolo Paulo contemplava o encerramento de seus dias terrenos. Consciente de que sua vida estava sendo derramada como uma oferta diante de Deus e que o momento de sua partida havia chegado, ele não expressou medo ou arrependimento. Com serenidade e convicção inabalável, escreveu a Timóteo afirmando que havia combatido o bom combate, completado a carreira que lhe fora designada e guardado a fé de maneira irrepreensível. Ele não media o sucesso de sua missão terrena pelo conforto ou pelo aplauso dos homens, mas pela fidelidade contínua ao chamado divino. Paulo sabia que o esperava a coroa da justiça, reservada pelo Senhor não apenas para ele, mas para todos os que amam a Sua manifestação gloriosa. Sua postura final revelou o ápice de uma vida inteiramente consagrada ao Reino eterno.', 'A verdadeira maturidade espiritual não se mede pela velocidade com que iniciamos uma jornada, mas pela constância com que a concluímos. Enfrentar pressões, fadiga e incertezas exige autogoverno e uma fidelidade inegociável aos princípios divinos. Guardar a fé é manter o coração alinhado à verdade de Deus quando o cansaço sugere atalhos fáceis. O combate da vida diária é vencido na escolha silenciosa de perseverar com retidão. Ao fixar os olhos na recompensa eterna prometida pelo Justo Juiz, você encontra o vigor necessário para cumprir seu dever com integridade até o fim.', 'Renove hoje seu compromisso com uma responsabilidade difícil sem buscar atalhos ou desculpas.', 'Terminar a jornada com fé é a maior vitória da vida.', 'No fim da vida, Paulo declarou com firmeza que combateu o bom combate e guardou a fé. A verdadeira vitória não está em evitar as batalhas, mas em permanecer fiel até o último passo. Que hoje você escolha a perseverança e a integridade em sua caminhada com Deus.', NOW()),
('1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'perseveranca', 'Perseverança', 'kids', 'kids', 9, 'Completando a Corrida com Jesus', '2 Timóteo 4:6-8', 'O apóstolo Paulo já estava bem velhinho e sabia que sua jornada nesta terra estava chegando ao fim. Ele escreveu uma cartinha muito especial para seu jovem amigo Timóteo. Como um atleta que corre com alegria ou uma abelhinha dedicada que leva o néctar até a colmeia sem desistir pelo caminho, Paulo disse: Combati o bom combate, terminei a corrida e guardei a fé. Ele não desanimou nos dias de tempestade nem parou nas subidas difíceis. Paulo segurou a mão de Jesus com todo o carinho em seu coração até o último instante. Agora, ele sabia que no céu havia uma linda coroa de justiça esperando por ele, entregue com amor pelo próprio Deus. Essa mesma bênção especial está guardada para todos aqueles que amam e esperam felizes a volta de Jesus.', 'Assim como uma plantinha que continua crescendo firme até dar lindas flores, nós também estamos em uma caminhada com Jesus. Às vezes o dia fica cansativo ou dá vontade de desistir de ser obediente e bondoso. Mas guardar a fé significa nunca soltar a mão de Deus, mesmo quando alguma coisa parece difícil. Quando escolhemos amar, perdoar e orar todos os dias, estamos completando nossa corrida com alegria e nos preparando para receber o abraço mais carinhoso do nosso Salvador.', 'Dar um abraço na família e dizer: Vamos seguir Jesus juntos até o fim!', 'Quem segura a mão de Jesus completa a corrida com vitória e alegria.', 'O apóstolo Paulo completou sua caminhada guardando a fé com amor e coragem até o fim.
Mesmo quando o dia parece difícil, Jesus nos dá forças para nunca desistirmos de fazer o bem.
Quem caminha firme com o Salvador receberá a linda coroa da vida em Seu Reino celestial.', NOW()),
('14d79e3b-c373-4ccf-800a-305595ea08d6', 'perseveranca', 'Perseverança', 'kids', 'teens', 9, 'O Bom Combate até o Fim', '2 Timóteo 4:6-8', 'O apóstolo Paulo encontrava-se em uma prisão fria em Roma, ciente de que o fim da sua vida nesta terra estava muito próximo. Ele não olhava para trás com arrependimento nem temia o que os homens podiam fazer ao seu corpo. Em sua última carta ao jovem Timóteo, Paulo declarou com firmeza que sua vida estava sendo derramada como uma oferta a Deus. Ele usou a imagem dos grandes atletas e soldados para resumir sua caminhada: combateu o bom combate, terminou a corrida e guardou a fé. Não importavam as correntes, as perseguições ou a solidão da cela; Paulo sabia que a sua fidelidade a Cristo valia tudo. Ele aguardava com total certeza a coroa da justiça, prometida pelo justo Juiz a todos os que amam a Sua vinda.', 'Na escola ou com os amigos, a tentação de abrir mão de valores cristãos para ser aceito é enorme. Manter a integridade quando todos zombam ou quando a rotina cansa parece pesado. Paulo nos ensina que a vida cristã não é um tiro rápido, mas uma corrida de resistência. Guardar a fé significa não negociar a verdade de Deus por popularidade ou comodidade momentânea. Cada escolha diária de obediência, mesmo sob zombaria ou cansaço, é parte do combate que você vence com Cristo.', 'Diga não a uma fofoca ou brincadeira inadequada hoje para honrar a Deus.', 'Quem guarda a fé em Cristo já garantiu a vitória eterna.', 'Mesmo preso e perto da morte, o apóstolo Paulo declarou com vitória: combateu o bom combate e guardou a fé.
A caminhada com Deus exige firmeza contra as pressões diárias.
Não negocie seus princípios por aceitação passageira; permaneça firme até o fim!', NOW()),
('f4569023-2eb4-4a5c-a856-278de5439d57', 'perseveranca', 'Perseverança', 'kids', 'young_adults', 9, 'O Combate da Fé Inegociável', '2 Timóteo 4:6-8', 'Em uma fria masmorra em Roma, o apóstolo Paulo sabia que o tempo de sua partida deste mundo havia chegado. Ele não olhava para trás com arrependimento nem com medo da morte iminente. Ao escrever sua última carta ao jovem discípulo Timóteo, Paulo declarou com firme convicção que havia combatido o bom combate, completado a carreira traçada por Deus e guardado a fé de forma inabalável. Sua vida inteira fora derramada como uma oferta de adoração ao Senhor. Paulo não buscava aplausos dos homens daquela época, pois tinha os olhos fixos na recompensa eterna: a coroa da justiça que o justo Juiz lhe entregaria no grande dia. Essa promessa, lembrou ele, não era exclusiva para si, mas para todos os que amam sinceramente a manifestação gloriosa de Cristo Jesus.', 'Guardar a fé exige disciplina rigorosa e firmeza de caráter quando ninguém está olhando. O mundo atual incentiva atalhos fáceis e compromissos com o erro, mas o jovem cristão é chamado a estabelecer limites morais intransigentes. A perseverança não se resume a um bom início, mas à fidelidade contínua nas decisões secretas de cada dia. Quando você resiste às pressões da juventude e obedece à Palavra, você não perde nada; você constrói um futuro sólido. Combater o bom combate significa manter a retidão e a lealdade a Cristo até a linha final.', 'Renuncie hoje a um hábito secreto que enfraquece sua disciplina espiritual e moral.', 'A verdadeira vitória consiste em permanecer fiel a Deus até o fim.', 'No fim da vida, Paulo declarou que combateu o bom combate e guardou a fé. A verdadeira vitória cristã não está nos aplausos do mundo, mas na disciplina diária e na fidelidade a Deus até o fim. Que hoje você escolha manter seus limites morais e perseverar firme em Cristo!', NOW()),
('caaccf38-ec6c-4d9b-8ec6-5296f16d7d27', 'perseveranca', 'Perseverança', 'personal', 'adulto', 10, 'A Vitória da Perseverança Fiel', 'Apocalipse 3:10-12', 'Na ilha de Patmos, o apóstolo João recebeu revelações gloriosas do Cristo ressurreto para fortalecer as igrejas perseguidas. Ao escrever à congregação de Filadélfia, o Senhor dirigiu palavras de ânimo singular. Aqueles cristãos, embora possuíssem pouca força material, guardaram com integridade a palavra da perseverança e não negaram o Seu santo nome. Cristo prometeu guardá-los na hora da provação que viria sobre a terra e ordenou: "Guarda o que tens, para que ninguém tome a tua coroa". Aos que perseverassem firmes até o fim, foi prometida uma posição perpétua e inabalável: seriam feitos colunas no templo de Deus, gravados com o Seu nome eterno. A fidelidade paciente daquela comunidade não apenas os sustentava nas aflições terrenas, mas garantia sua vitória definitiva no reino celestial vindouro.', 'A maturidade espiritual se manifesta no autogoverno e na lealdade inegociável aos princípios divinos quando as pressões aumentam. Guardar o que temos significa preservar o temor a Deus, o caráter reto e a obediência diária, sem ceder ao desânimo ou às tentações do atalho. A promessa de se tornar uma coluna no templo divino nos lembra que a perseverança forja estabilidade eterna. Quando você decide permanecer fiel nas pequenas responsabilidades e nos testes cotidianos, Deus sustenta seus passos e assegura uma recompensa que jamais poderá ser tirada ou destruída pelas circunstâncias da vida.', 'Identifique um princípio inegociável e decida cumpri-lo com firmeza hoje mesmo.', 'Quem persevera fiel com Cristo torna-se uma coluna inabalável na eternidade.', 'Em Apocalipse 3:10-12, Jesus promete guardar os fiéis e fazer dos vencedores colunas firmes em Seu templo. A perseverança nas lutas diárias não é em vão; ela forja o caráter e garante a recompensa eterna. Guarde com integridade a sua fé e permaneça inabalável diante dos testes da vida.', NOW()),
('463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'perseveranca', 'Perseverança', 'kids', 'kids', 10, 'Colunas Fortes na Casa de Deus', 'Apocalipse 3:10-12', 'O apóstolo João recebeu uma mensagem muito especial de Jesus para a pequena igreja da cidade de Filadélfia. Jesus sabia que aquelas pessoas guardaram Sua palavra com amor e não desistiram da fé, mesmo quando tudo parecia difícil. Então, o Senhor fez uma promessa linda e cheia de carinho: Ele guardaria cada um deles nos momentos de provação e viria logo ao encontro deles. Jesus disse que todo aquele que perseverar e vencer será transformado em uma coluna forte e inabalável no templo de Deus, de onde nunca mais precisará sair. Como árvores com raízes fundas que suportam o vento forte sem cair, os amigos fiéis de Jesus recebem uma coroa preciosa e o Seu próprio e maravilhoso nome gravado com amor para sempre.', 'Assim como uma grande árvore fica firme durante a tempestade porque suas raízes estão bem presas na terra, nosso coração fica seguro quando não desistimos de obedecer a Jesus. Quando você escolhe falar a verdade, perdoar um amigo ou esperar com paciência mesmo sem vontade, você está sendo forte como uma coluna. Jesus vê cada pequeno esforço com muito amor e promete uma grande recompensa no céu: a certeza de viver para sempre pertinho Dele, com uma linda coroa de vitória que ninguém pode tirar.', 'Dê um abraço apertado em alguém hoje e diga: Jesus nos faz fortes e vencedores!', 'Quem permanece firme com Jesus recebe a coroa da vitória eterna.', 'Em Apocalipse 3, Jesus promete que quem perseverar na fé será como uma coluna forte em Seu templo e receberá a coroa da vida. Mesmo diante dos desafios, confiar no Senhor nos mantém firmes como árvores com raízes profundas. A recompensa eterna de Jesus está garantida para todos os que permanecem fiéis ao Seu amor!', NOW()),
('ede927a1-428a-460a-b4f6-279b5a1eff57', 'perseveranca', 'Perseverança', 'kids', 'teens', 10, 'A Recompensa Eterna dos Vitoriosos', 'Apocalipse 3:10-12', 'Na visão concedida ao apóstolo João na ilha de Patmos, o próprio Senhor Jesus dirigiu uma mensagem de ânimo à igreja de Filadélfia. Aquela pequena comunidade enfrentava grandes pressões e oposições diárias, mas guardou com fidelidade a palavra da perseverança de Cristo. Por causa dessa firmeza inabalável, Jesus prometeu protegê-los na hora da provação que viria sobre o mundo. O Senhor os advertiu a guardar com firmeza o que já tinham, para que ninguém tomasse a sua coroa. A promessa para o vencedor era grandiosa: ele seria feito uma coluna inabalável no santuário de Deus, jamais saindo dali. Além disso, receberia gravado em si o santo nome do Senhor e o nome da nova Jerusalém celestial. A lealdade paciente na terra encontraria a sua recompensa máxima na glória eterna ao lado do Salvador.', 'Manter a fé e a integridade na escola ou entre amigos exige resistir à tentação de ceder às pressões do grupo. Quando você escolhe não colar, não zombar do colega e defender a verdade, mesmo sendo criticado, você demonstra a perseverança bíblica. As dificuldades e testes desta vida são passageiros, mas a recompensa de Deus para os fiéis é eterna. Guarde com firmeza os princípios de Cristo no seu dia a dia. A sua fidelidade nos pequenos desafios de hoje constrói uma vida inabalável na presença do Senhor.', 'Mantenha a integridade em uma escolha difícil hoje, sem ceder à pressão alheia.', 'Quem permanece firme com Cristo recebe uma coroa de vitória eterna.', 'Em Apocalipse 3:10-12, Jesus promete aos fiéis de Filadélfia que aqueles que guardam Sua palavra com perseverança serão colunas eternas no templo de Deus e receberão a coroa da vitória.
Diante das pressões diárias e desafios com amizades ou responsabilidades, manter a firmeza e a integridade cristã garante uma recompensa inabalável nos céus.
Seja leal a Cristo hoje e guarde aquilo que Ele lhe confiou.', NOW()),
('594dc0b8-ca92-4ab7-8ec9-22184c981304', 'perseveranca', 'Perseverança', 'kids', 'young_adults', 10, 'A Coroa da Vitória Eterna', 'Apocalipse 3:10-12', 'O apóstolo João, exilado na ilha de Pátmos, recebeu revelações gloriosas do Cristo ressurreto para as igrejas da Ásia Menor. À pequena e fiel congregação de Filadélfia, o Senhor dirigiu palavras de encorajamento e triunfo. Aqueles crentes enfrentavam forte oposição, mas guardaram a palavra da paciência de Cristo e não negaram o Seu nome. Jesus prometeu guardá-los na hora da provação que viria sobre a terra. Ele os advertiu a reter firmemente o que possuíam, para que ninguém tomasse a sua coroa. Ao vencedor, o Senhor fez promessas eternas: seria feito coluna inabalável no templo de Deus, de onde jamais sairia, e receberia a inscrição do santo nome do Senhor e da nova Jerusalém. A perseverança deles no presente garantia uma recompensa gloriosa e indestrutível para a eternidade.', 'Guardar os mandamentos de Cristo quando ninguém está olhando exige coragem e disciplina diária. O mundo oferece atalhos sedutores e pressiona os jovens a negarem seus princípios por aprovação passageira. No entanto, a fidelidade nas pequenas escolhas constrói um caráter inabalável para o futuro. Jesus não promete uma jornada sem testes, mas garante a vitória final a quem permanece firme. Quem retém a fé e rejeita o pecado não perde nada deste mundo, pois ganha uma coroa eterna e um lugar seguro na presença de Deus. Seja fiel até o fim.', 'Renuncie hoje a um hábito secreto que enfraquece sua disciplina espiritual e moral.', 'Quem persevera com Cristo recebe a recompensa que ninguém pode roubar.', 'Em Apocalipse 3, Cristo exorta Sua igreja a guardar a fé e reter sua coroa diante das provações.
A perseverança nas escolhas diárias e a fidelidade moral produzem uma recompensa inabalável e eterna.
Mantenha-se firme no Senhor hoje para colher a vitória prometida!', NOW());

INSERT INTO "public"."dev_questions" ("id", "lesson_id", "question_text", "display_order") VALUES
('49e3a387-6405-480e-bebd-8dac1c939185', 'd62c3014-5880-404f-a37c-88353ae2dc55', 'De acordo com Gálatas 6:9-10, qual é a condição para que a colheita no tempo certo aconteça?', 1),
('8f8a4bfa-4e00-4078-8bde-76062bcff870', 'd62c3014-5880-404f-a37c-88353ae2dc55', 'Em quais áreas da sua vida diária o cansaço mais tem tentado você a deixar de fazer o bem?', 2),
('e6a667f8-a54a-4770-bce6-445363569e22', 'd62c3014-5880-404f-a37c-88353ae2dc55', 'Que atitude prática de serviço você manterá com firmeza esta semana, mesmo sem ver frutos imediatos?', 3),
('808c2f41-373b-480b-b1e9-e7a58feecc89', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'O que o apóstolo Paulo ensinou que vai acontecer se não desistirmos de fazer o bem?', 1),
('7f2847d7-61ed-47f2-af43-443035b55f06', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'Você já se sentiu cansado ou triste ao tentar ser bondoso e ninguém notar?', 2),
('a9729768-9d9b-48b4-8854-0742df3b5d06', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'Qual sementinha de amor ou ajuda você pode plantar na sua casa hoje?', 3),
('ae739211-3b04-4367-afe4-2255ea83d3be', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'O que o apóstolo Paulo prometeu àqueles que não desanimam de fazer o bem?', 1),
('6e208c3b-a2a8-46e4-a7a4-d4f495053d2b', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'Em quais situações do seu dia você sente mais cansaço ou vontade de desistir de agir corretamente?', 2),
('44d5f1cc-65c9-439a-841d-67ca3a4bc22e', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'Qual atitude boa você precisa continuar praticando nesta semana mesmo sem ver resultados imediatos?', 3),
('d18f6ade-1b78-4895-9968-6aeca79d52a5', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'O que o apóstolo Paulo prometeu aos crentes que não desfalecerem no bem?', 1),
('7eb4ddab-7fb1-4402-a59e-c6d121578fa4', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'Em quais momentos você se sente tentado a desistir de manter a disciplina moral?', 2),
('521d259c-998b-4c6e-b4dc-6748e23ce2a7', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'Qual atitude concreta você tomará hoje para perseverar no bem, mesmo sem reconhecimento imediato?', 3),
('d952b326-a1d3-4844-9e8c-ea9cecefa943', 'cc338eb5-d5c2-44e6-8180-056d05736cfa', 'O que Tiago afirma ser o fruto direto da provação da nossa fé?', 1),
('7061dd84-81af-4808-af76-b3ebc9700e67', 'cc338eb5-d5c2-44e6-8180-056d05736cfa', 'Em quais situações difíceis de sua rotina você tem sido tentado a desistir ou murmurar?', 2),
('12ea98b6-243b-411d-8a48-e8c77b8bda14', 'cc338eb5-d5c2-44e6-8180-056d05736cfa', 'Qual atitude concreta de paciência e integridade você adotará no próximo obstáculo que surgir?', 3),
('226aa3bb-9edb-4740-90b3-cb019461c281', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'O que o apóstolo Tiago ensinou sobre o que acontece com a nossa fé durante as dificuldades?', 1),
('79295135-279f-4701-ba29-25c800a5e0ff', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'Qual foi a coisa mais difícil que você tentou fazer hoje e deu vontade de desistir?', 2),
('74307814-b535-466b-aac3-cf541309a3cd', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'O que podemos fazer juntos em casa quando uma tarefa parecer difícil ou cansativa?', 3),
('1d9ad252-5142-457c-aeb8-4e6e9c9b2baf', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Segundo Tiago, qual é o fruto gerado quando a nossa fé é provada?', 1),
('e20f1c62-b2c2-4d55-8075-1a9887b25f0f', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Qual dificuldade recente na escola ou em casa mais desafiou a sua paciência?', 2),
('b13384ea-0ff4-4ac5-9fce-6a59b1bf3a03', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Que atitude prática você pode tomar para não desanimar diante das cobranças diárias?', 3),
('a9e1558c-ff6f-47cb-9df6-f74075b86b8b', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Segundo Tiago, qual é o resultado gerado pela prova da nossa fé?', 1),
('6f215ec1-9180-496a-b2c6-e81e412583af', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Em quais decisões secretas você sente maior pressão para abrir mão da disciplina?', 2),
('f0c4b974-9596-466c-ba16-016a4fe01a97', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Qual limite moral você precisa firmar hoje para não ceder às facilidades?', 3),
('db639653-4fb5-4be4-b82d-f89d173cbeda', '9a1aaa1c-2584-452e-9c66-b8c56136d551', 'O que sustentava a certeza de Paulo ao encarar o fim de sua vida terrena?', 1),
('50138bc6-02d9-48c5-850c-aff10e92d8e6', '9a1aaa1c-2584-452e-9c66-b8c56136d551', 'Quais distrações ou cansaços têm tentado desviar você de completar sua caminhada com fidelidade?', 2),
('b5bcf10f-9a3d-444e-b71d-859bd683f537', '9a1aaa1c-2584-452e-9c66-b8c56136d551', 'Que atitude concreta você precisa tomar hoje para manter sua fé inegociável diante dos desafios?', 3),
('b99aac0a-7242-4da6-b558-1a03eaebf482', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'O que o apóstolo Paulo disse que guardou até o fim da sua vida?', 1),
('bb1c4152-31bc-456c-91a3-789ec4261c66', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'Em quais momentos do seu dia você sente mais dificuldade para continuar sendo obediente?', 2),
('83393b45-21bb-4fcf-8b2d-39f75bb9cbef', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'O que podemos fazer juntos em casa para nunca esquecer de amar a Jesus?', 3),
('821dfcc0-6109-4844-8335-96de97ec6256', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'O que Paulo quis dizer ao afirmar que combateu o bom combate e guardou a fé?', 1),
('c5ffc07e-15e5-4874-bff0-ea4cb5f774c9', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'Em quais momentos na escola ou no grupo de amigos você sente que a sua fé é colocada à prova?', 2),
('37a6483a-4b82-4b5a-9cf9-7fdfa525d25e', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'Qual princípio cristão você precisa se comprometer a nunca negociar a partir de hoje?', 3),
('c5748298-104e-463d-a9b6-b774db833d4d', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'O que Paulo quis dizer ao afirmar que combateu o bom combate e guardou a fé?', 1),
('13f51abd-8326-462c-84f6-e3dad333eb0d', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'Quais pressões cotidianas ou escolhas privadas têm testado seus limites morais e sua perseverança?', 2),
('1475b408-678a-4e25-9ed4-04a2a31f5e34', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'Que decisão prática e corajosa você precisa tomar hoje para manter sua fé pura?', 3),
('bc02e2f1-287b-4967-a538-2a3d381d451f', 'caaccf38-ec6c-4d9b-8ec6-5296f16d7d27', 'O que Jesus prometeu àqueles que guardaram a palavra da Sua perseverança?', 1),
('145ffc4a-ce67-40de-9014-2de5684f49c3', 'caaccf38-ec6c-4d9b-8ec6-5296f16d7d27', 'Em quais áreas da sua rotina você sente a tentação de afrouxar sua fidelidade?', 2),
('b63f6fde-ca4e-4797-bf39-c8f7d56343e8', 'caaccf38-ec6c-4d9b-8ec6-5296f16d7d27', 'Que atitude prática você tomará hoje para guardar a sua coroa com integridade?', 3),
('8466d526-5966-4f07-b6df-eb6279588dcb', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'O que Jesus prometeu que o vencedor seria no templo de Deus?', 1),
('7e83736c-ed66-4368-a9e8-103d682fe505', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'Quando você sente vontade de desistir de ser obediente, o que pode te ajudar a ficar firme?', 2),
('c4309dfa-7caa-4143-b9a1-81d23563378f', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'Que atitude de amor e obediência nós podemos praticar juntos amanhã?', 3),
('b75a3f0b-7e11-448d-8248-2859f18e7ecc', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'Qual promessa Jesus fez aos fiéis que perseverassem e guardassem a Sua palavra?', 1),
('7108dab7-8d60-47c2-b8f4-a946d7786864', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'Em quais situações na escola ou com amigos é mais difícil manter a firmeza da fé?', 2),
('f5596038-6082-447c-9648-d2e8da134423', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'O que você pode fazer hoje para não abrir mão dos valores cristãos diante da pressão?', 3),
('de5fe4a0-7838-4ffc-839f-6fc0a61e809c', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Que promessas Jesus fez em Apocalipse para aqueles que guardam a Sua palavra com paciência?', 1),
('fead238f-27a5-4649-acd3-0125d85d9eaa', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Quais tentações ou pressões sociais atuais mais testam sua firmeza e fidelidade a Deus?', 2),
('5abd7e81-fb4c-416c-8d74-1970d7dc97b5', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Qual decisão prática você tomará hoje para manter sua fé inabalável diante das provações?', 3);

INSERT INTO "public"."dev_prayers" ("id", "lesson_id", "role", "text_content", "display_order") VALUES
('8cf71939-b774-4f3c-8136-22fc1081ba73', 'd62c3014-5880-404f-a37c-88353ae2dc55', 'Individual', 'Senhor Deus, reconheço que muitas vezes o cansaço e a demora dos frutos tentam enfraquecer minha disposição para o bem. Concede-me autogoverno, paciência e firmeza para perseverar em cada ato de obediência e serviço. Guarda o meu coração contra o desânimo e ajuda-me a confiar plenamente que o Teu tempo para a colheita é perfeito e fiel. Em nome de Jesus, amém.', 1),
('fe0f565c-deaf-4198-beef-7c770394923d', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'Pai', 'Senhor, ensina nossos corações a perseverar na prática do bem sem desanimar com a espera.', 1),
('f5209558-153c-43ed-a3dd-5fa7dd4685ed', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'Filho', 'Jesus, ajuda meu coração a ser obediente e carinhoso, mesmo quando eu me sentir cansado.', 2),
('2f502318-0ee3-4e84-8866-1a6c24ba1783', '45a668ed-ab58-4243-a6a5-f501816e7a0c', 'Juntos', 'Pai do Céu, rega a nossa casa com Teu amor para colhermos frutos de paz no Teu tempo. Amém.', 3),
('0ea3f56d-182a-469b-b666-501fec52824d', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'Pai', 'Senhor, dai-nos paciência para perseverar no bem e guiar nossa família com firmeza e fé.', 1),
('542ba9c0-152e-4a6c-9cc7-13e0c9f8ab1a', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'Filho', 'Pai celestial, ajuda-me a não desanimar nas minhas responsabilidades e a sempre escolher o caminho certo.', 2),
('22ee807c-f584-4364-b935-9eeb44085c0f', 'b72d64be-0e3c-44d7-9ca1-fea7fe11a8d9', 'Juntos', 'Deus eterno, confiamos que a nossa colheita virá no Teu tempo. Amém.', 3),
('6e254e50-7ddf-48ac-8347-355772d320a9', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'Pai', 'Senhor, capacita-me a guiar meu filho pelo exemplo diário de constância e integridade cristã.', 1),
('9e3c8219-5461-4045-b779-86d63c683ae2', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'Filho', 'Pai celestial, fortalece minha vontade para rejeitar o pecado e perseverar no caminho correto.', 2),
('4f6e0227-20c8-4122-94f1-7c0f11e647ea', 'c674dd4f-e06e-43ae-902c-f5b321cc34bd', 'Juntos', 'Senhor Deus, concede-nos perseverança inabalável para semearmos o bem até a colheita eterna. Amém.', 3),
('493e86c7-c23e-45b9-b4ac-1391d3630dcb', 'cc338eb5-d5c2-44e6-8180-056d05736cfa', 'Individual', 'Senhor meu Deus, concede-me sabedoria para compreender o valor da disciplina e das provações. Que em meio às dificuldades do dia a dia eu não me deixe vencer pela murmuração ou pela pressa. Forja em mim um caráter íntegro e paciente, capaz de suportar as pressões com fidelidade e autogoverno. Que a Tua graça me sustente em retidão até o fim. Amém.', 1),
('ce6575b9-f3b0-496d-93e3-236bca8171b9', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'Pai', 'Senhor, ajuda nossos filhos a entenderem que os momentos difíceis nos ensinam a crescer com raízes firmes em Ti.', 1),
('59d8bd45-909f-4f96-bd3b-eba014973902', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'Filho', 'Papai do Céu, me dá paciência e bom ânimo quando eu não conseguir fazer algo de primeira.', 2),
('e5a3acb1-53b3-43db-9762-dad41d37ea3d', 'cda58e7a-1883-4972-a7f5-8493b614cf30', 'Juntos', 'Amém! Ensina nossa família a confiar em Ti e a nunca desistir diante das dificuldades.', 3),
('3613cf19-7190-4a58-a6c8-408514a09faf', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Pai', 'Senhor, ajuda-me a guiar minha casa com firmeza e paciência em cada provação.', 1),
('4e08ec9a-8d37-482c-bd1c-8a6ba9776fd9', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Filho', 'Deus, dá-me coragem para não desistir diante dos estudos e das pressões diárias.', 2),
('436e9557-5887-4710-8cef-080b91e338ec', '98af54c0-81b3-47d2-a965-cf47f1b3c953', 'Juntos', 'Pai celestial, molda o nosso caráter para sermos fiéis e perseverantes até o fim. Amém.', 3),
('6b6814b5-0cf0-40d0-a9e8-0f8276819885', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Pai', 'Senhor, dá-me sabedoria para ensinar meu filho a amar a disciplina e a integridade.', 1),
('13973067-8e99-4928-8c2a-21e7c28cecb7', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Filho', 'Deus, fortalece meu coração para suportar as provações e fazer escolhas corretas no secreto.', 2),
('c0dfbe04-5312-446a-9d55-762177d97b30', '7e35da2c-0ccf-44a6-8aab-2d043de72208', 'Juntos', 'Pai celestial, ajuda a nossa família a perseverar na verdade em qualquer situação. Amém.', 3),
('2bfe9393-0a9d-4581-b81b-014e66c68276', '9a1aaa1c-2584-452e-9c66-b8c56136d551', 'Individual', 'Senhor meu Deus, fortalece meu espírito para que eu permaneça firme em Tua verdade. Dá-me autogoverno e paciência para suportar as tribulações sem abrir mão da minha integridade. Que a minha vida seja uma corrida marcada pela perseverança e que, ao final da minha jornada, eu possa testemunhar que guardei a fé inabalável em Ti. Amém.', 1),
('ade7c013-8646-4a4c-aa8e-d740a9d7b799', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'Pai', 'Senhor, ajuda nossa família a guardar a fé e a seguir Teus passos todos os dias.', 1),
('1557e9d9-1e7b-4530-80b8-1080cb3d0b86', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'Filho', 'Papai do Céu, segura bem forte a minha mãozinha para eu nunca desistir de Te amar.', 2),
('d1f7a583-e6ac-4ef7-8231-01f0a8faf36c', '1d8b5a2b-7fd6-4d1b-a953-124e5b1219c3', 'Juntos', 'Obrigado, Jesus, por nos dar forças para corrermos juntos até o Teu Reino. Amém!', 3),
('bf603c7b-10d4-4c36-a45e-042ab02ff037', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'Pai', 'Senhor, dá-nos firmeza para liderar esta casa no Teu caminho, sem desviar nem desanimar diante das pressões do mundo.', 1),
('a7b46bfb-1e39-40e4-a0e7-81d4c1f119ba', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'Filho', 'Jesus, ajuda-me a não ter vergonha da minha fé e a permanecer fiel a Ti mesmo quando for difícil.', 2),
('058ffa19-6a3b-419e-bbcc-1941848b2000', '14d79e3b-c373-4ccf-800a-305595ea08d6', 'Juntos', 'Pai amado, ajuda a nossa família a combater o bom combate até o fim, guardando sempre a fé. Amém.', 3),
('2afdad9f-8bc2-45e4-a72e-682f0e0f1fe0', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'Pai', 'Senhor, dá-me sabedoria e firmeza para liderar pelo exemplo, ensinando a fidelidade aos Teus mandamentos.', 1),
('687286f2-ed32-49bd-ab7d-e5d515094ea7', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'Filho', 'Pai celeste, fortalece meu coração para rejeitar as ilusões do pecado e perseverar em retidão nas minhas escolhas.', 2),
('b9090664-ff7f-4547-8dcc-feba6e5532a9', 'f4569023-2eb4-4a5c-a856-278de5439d57', 'Juntos', 'Senhor Deus, ajuda a nossa família a guardar a fé inegociável até o fim da nossa caminhada. Amém.', 3),
('421e6a56-7bbf-43b4-a48a-51a1540c8ade', 'caaccf38-ec6c-4d9b-8ec6-5296f16d7d27', 'Individual', 'Senhor Deus, reconheço que a verdadeira firmeza vem da comunhão Contigo. Fortalece o meu espírito para que eu não vacile diante das provações diárias. Ensina-me a manter a integridade, a guardar a fé e a agir com fidelidade inabalável em cada decisão. Que a Tua promessa eterna guie os meus passos e firme a minha conduta hoje e sempre. Amém.', 1),
('6fa21248-dd64-43f1-a073-10473133e38e', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'Pai', 'Senhor, ajuda-nos a ensinar nossos filhos a permanecerem firmes e fiéis ao Teu amor todos os dias.', 1),
('035597ac-2575-4ca1-8981-e1b6dc411582', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'Filho', 'Jesus, obrigado por cuidar de mim e me dar forças para nunca desistir do que é certo.', 2),
('a787873d-9680-44fb-b9d9-db9b5d97289f', '463f5d9f-0be0-4bc7-8b8c-af98099c1593', 'Juntos', 'Amém! Cremos na Tua promessa e queremos viver para sempre seguros em Tua presença.', 3),
('5d9bb63e-e680-4c79-9b1a-0591d79bdab9', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'Pai', 'Senhor, fortalece nossos filhos contra as pressões do mundo e dá-nos sabedoria para sermos modelos de perseverança inabalável.', 1),
('a3ba157f-6309-4504-b86f-91ce85cb20d6', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'Filho', 'Jesus, ajuda-me a ser fiel nas minhas amizades e decisões diárias, sem ter medo de defender o que é certo.', 2),
('6fa7b40b-7b6a-477a-8493-9fe9b5a8eb30', 'ede927a1-428a-460a-b4f6-279b5a1eff57', 'Juntos', 'Pai Celestial, guardamos Tua Palavra no coração para vencermos os testes da vida e reinarmos eternamente contigo. Amém.', 3),
('ccf89816-e3fb-45b7-9088-49ea5dcbbe12', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Pai', 'Senhor, fortalece meu filho para resistir às pressões do mundo e permanecer inabalável na verdade.', 1),
('8275bcc2-3856-49af-bda2-ffc620e2b537', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Filho', 'Pai celestial, dá-me coragem para honrar Teu nome nas minhas decisões secretas e guardar a minha coroa.', 2),
('faeeaf43-2cbb-4b04-a2c5-e4caf6de2ce9', '594dc0b8-ca92-4ab7-8ec9-22184c981304', 'Juntos', 'Senhor Jesus, ajuda nossa família a perseverar com integridade até recebermos a Tua recompensa eterna. Amém.', 3);

