-- 1. Atualizar a constraint de número de lições para permitir até 30 lições por tema
ALTER TABLE "public"."dev_lessons" 
  DROP CONSTRAINT IF EXISTS "dev_lessons_lesson_number_check",
  ADD CONSTRAINT "dev_lessons_lesson_number_check" CHECK ((lesson_number >= 1) AND (lesson_number <= 30));

-- 2. Novas Lições de Honestidade (Noites 7 a 10 - Novo Testamento)
INSERT INTO "public"."dev_lessons" ("id", "theme_id", "theme_name", "development_mode", "age_group", "lesson_number", "title", "biblical_reference", "biblical_story", "reflection", "challenge", "final_message", "share_summary", "created_at") VALUES
('a1a87603-fb01-4373-b3af-4aa71ca1db45', 'honestidade', 'Honestidade', 'personal', 'adulto', 7, 'A Coragem de Reparar os Erros', 'Lucas 19:1-9', 'Jesus entrou em Jericó e atravessava a cidade. Havia ali um homem rico chamado Zaqueu, chefe dos cobradores de impostos. Sendo de baixa estatura, ele correu adiante e subiu em uma figueira brava para ver Jesus passar. Ao chegar àquele lugar, Jesus olhou para cima e lhe disse: "Zaqueu, desça depressa, pois hoje preciso ficar em sua casa". Zaqueu desceu depressa e o recebeu com grande alegria. A multidão, ao ver isso, murmurava dizendo que Jesus havia entrado para ser hóspede de um pecador. Então Zaqueu levantou-se e disse ao Senhor: "Eis que dou a metade dos meus bens aos pobres; e, se extorqui algo de alguém, restituo quatro vezes mais". Jesus lhe declarou: "Hoje houve salvação nesta casa, pois este homem também é filho de Abraão".', 'O verdadeiro alinhamento moral com Deus exige mais do que pesar de consciência; requer ação concreta. Zaqueu não ofereceu justificativas ou promessas vagas, mas assumiu a responsabilidade pelos danos causados, abrindo mão do ganho desonesto. Integridade genuína envolve a coragem de examinar o passado, reparar prejuízos financeiros ou morais causados a outros e adotar transparência absoluta no trato com os bens. Quando a honestidade guia nossas decisões, o arrependimento deixa de ser mero discurso e se torna retidão prática na administração da vida e dos relacionamentos.', 'Identifique uma pendência do passado e inicie hoje a reparação devida com retidão.', 'A integridade autêntica conserta o passado para edificar um futuro reto.', 'A verdadeira honestidade vai além do arrependimento: ela exige reparação e atitudes práticas. Assim como Zaqueu restituiu o que obteve injustamente, somos chamados a consertar pendências e viver com retidão. Quando corrigimos nossos erros, a integridade se estabelece em nossa história.', NOW()),
('3e827ef6-0d0e-4202-a727-bc761fc1e368', 'honestidade', 'Honestidade', 'kids', 'kids', 7, 'Zaqueu e a Coragem de Consertar', 'Lucas 19:1-9', 'Jesus entrou na movimentada cidade de Jericó. Naquele lugar vivia um homem chamado Zaqueu, chefe dos cobradores de impostos e muito rico. Ele queria muito ver Jesus, mas não conseguia porque era muito baixinho e a multidão cobria sua visão. Então, Zaqueu correu na frente de todos e subiu nos galhos de uma grande figueira para poder enxergá-lo. Quando Jesus passou por ali, olhou para cima e chamou: "Zaqueu, desça depressa, pois hoje devo ficar em sua casa". Ele desceu feliz e acolheu o Mestre com festa. Diante do amor de Jesus, Zaqueu decidiu mudar suas atitudes e disse: "Senhor, darei metade dos meus bens aos pobres e, se tirei algo de alguém injustamente, pagarei quatro vezes mais". Jesus declarou alegremente que a salvação havia entrado naquela casa.', 'Assim como um jardineiro cuida de um galho quebrado para a planta voltar a florir, a honestidade conserta o que estragamos. Zaqueu percebeu que não bastava apenas pedir desculpas; ele quis devolver o que tirou e curar a tristeza que causou. Quando pegamos um brinquedo sem pedir ou dizemos algo que machuca, o coração fica pesado. Mas, quando confessamos e consertamos o erro com carinho e verdade, nosso lar se enche de paz e a alegria verdadeira brota outra vez.', 'Devolva um objeto emprestado ou peça desculpas sinceras a quem você magoou hoje.', 'A honestidade verdadeira sempre repara os erros com amor e atitudes.', 'Aprendemos hoje com Zaqueu que a honestidade de verdade não fica só nas palavras, mas conserta os erros do passado.
Quando reconhecemos nossas falhas e restituímos com amor, a alegria de Jesus enche a nossa casa.
Conserte hoje o que for preciso e viva em paz!', NOW()),
('8b983b9d-9d83-4e15-85c0-8742f695f759', 'honestidade', 'Honestidade', 'kids', 'teens', 7, 'Zaqueu: A Coragem de Reparar', 'Lucas 19:1-9', 'Ao entrar em Jericó, Jesus atraiu uma multidão. Entre o povo estava Zaqueu, o chefe dos cobradores de impostos, homem rico que enriquecera cobrando valores abusivos. Por ser de baixa estatura, ele não conseguia ver Jesus no meio da multidão. Determinado, correu à frente e subiu em uma figueira brava para observá-lo. Ao chegar àquele lugar, Jesus olhou para cima e disse para Zaqueu descer depressa, pois ficaria em sua casa. Ele desceu com alegria e o recebeu. Vendo a graça do Mestre, a consciência de Zaqueu despertou. Diante de todos, ele declarou que daria metade dos seus bens aos pobres e devolveria quatro vezes mais a quem tivesse prejudicado. Vendo essa atitude genuína de mudança, Jesus proclamou que a salvação havia chegado àquela casa, pois o Filho do Homem veio buscar e salvar o perdido.', 'A verdadeira honestidade vai além de admitir o erro; ela exige a coragem de consertar o que foi quebrado. Zaqueu não ofereceu desculpas vazias, mas decidiu reparar o prejuízo que causou aos outros. Na escola, na família ou com amigos, quando enganamos alguém, pegamos algo sem permissão ou espalhamos uma mentira, o arrependimento sincero se prova na ação. Ser íntegro diante de Deus significa ter a bravura de pedir perdão, devolver o que não é nosso e restaurar a confiança por meio de atitudes práticas e transparentes.', 'Devolva algo emprestado ou peça desculpas sinceras a quem você prejudicou esta semana.', 'A verdadeira honestidade conserta o passado e constrói um futuro limpo.', 'Noite 7: Zaqueu e a Restituição Sincera.
O encontro com Jesus levou Zaqueu a reparar seus erros com ações práticas.
A honestidade bíblica não dá desculpas: ela restaura a verdade e traz paz ao coração.', NOW()),
('c34441fb-8e9e-4433-8ece-4dfa022ba911', 'honestidade', 'Honestidade', 'kids', 'young_adults', 7, 'Honestidade que Restitui e Transforma', 'Lucas 19:1-9', 'Ao entrar em Jericó, Jesus atravessava a multidão quando um homem rico chamado Zaqueu, chefe dos publicanos, procurava vê-lo. Por ser de baixa estatura, Zaqueu correu adiante e subiu em uma figueira brava para enxergar o Mestre que passava por ali. Ao chegar àquele lugar, Jesus olhou para cima e disse que era necessário pousar em sua casa naquele dia. Zaqueu desceu depressa e o recebeu com imensa alegria, enquanto o povo murmurava por Cristo se hospedar com um pecador. Naquele encontro transformador, Zaqueu levantou-se diante de todos e declarou que daria a metade dos seus bens aos pobres e, se houvesse defraudado alguém, devolveria quatro vezes mais. Jesus então proclamou que a salvação havia entrado naquela casa.', 'O verdadeiro arrependimento não permanece apenas em palavras, mas se manifesta em atitudes concretas de reparação. Quando Zaqueu encontrou Cristo, compreendeu que a honestidade exigia acertar as contas do passado, devolver o que não era seu e viver com total retidão material. Para os jovens que constroem o próprio futuro, o caráter sólido começa nas escolhas secretas e na coragem de devolver itens emprestados, admitir fraudes acadêmicas e confessar pequenos ganhos desonestos. A graça divina nos impulsiona a reparar o dano causado ao próximo, tornando a integridade um estilo de vida visível.', 'Devolva hoje qualquer objeto que pegou emprestado ou admita um erro recente a alguém.', 'Quem teme a Deus não esconde o erro, mas o repara com coragem.', 'Hoje refletimos sobre Zaqueu (Lucas 19:1-9) e o valor da honestidade que repara o passado.
A verdadeira fé produz a coragem de restituir o que foi tirado e confessar erros.
Integridade de verdade se prova nas atitudes práticas e na reparação do dano ao próximo.', NOW()),
('3759048f-684b-4335-8159-138ec6096faa', 'honestidade', 'Honestidade', 'personal', 'adulto', 8, 'Verdade e Integridade nas Relações', 'Efésios 4:22-25', 'O apóstolo Paulo, escrevendo aos crentes reunidos em Éfeso, exorta a comunidade a abandonar os velhos costumes corrompidos pelo engano. Ele apresenta a transformação espiritual não apenas como um sentimento interior, mas como uma mudança visível de conduta diária. O apóstolo ensina que a nova vida em Cristo exige despojar-se da falsidade, como quem retira vestes sujas, e vestir-se da justiça e da verdadeira santidade. Nesse chamado solene, Paulo ordena expressamente: deixem a mentira e falem a verdade cada um ao seu próximo. O motivo apresentado é profundo e orgânico: pertencemos uns aos outros como membros de um só corpo espiritual. O engano mútuo fere a própria comunidade, enquanto a sinceridade nas palavras sustenta a firmeza, a comunhão e a paz duradoura entre os irmãos.', 'A mentira corrói a convivência e destrói os laços de confiança no lar e no trabalho. Quando ocultamos fatos ou distorcemos palavras para obter vantagens ou evitar repreensões, prejudicamos diretamente aqueles com quem compartilhamos a vida. A integridade cristã exige autogoverno e coragem para assumir a verdade sem subterfúgios. Falar com transparência e respeito fortalece os relacionamentos e edifica uma conduta sólida diante de Deus e dos homens.', 'Substitua hoje qualquer omissão por uma conversa franca e respeitosa com alguém próximo.', 'A integridade nas palavras edifica relacionamentos fortes e honra a Deus.', 'A verdadeira comunhão exige o abandono da mentira e o compromisso com a verdade. Como membros do mesmo corpo, nossas palavras devem edificar e proteger a confiança mútua. Cultive hoje conversas sinceras e transparentes no lar e nas amizades.', NOW()),
('cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'honestidade', 'Honestidade', 'kids', 'kids', 8, 'Trocando a Roupa pela Verdade', 'Efésios 4:22-25', 'O apóstolo Paulo escreveu uma carta cheia de carinho para a igreja de Éfeso. Ele ensinou que seguir a Jesus é como tirar uma roupa velha, suja de lama, e vestir uma roupa nova, limpa e brilhante. Paulo explicou que a mentira faz parte daquela roupa velha que não serve mais. Agora, quem ama a Jesus deve falar sempre a verdade com o seu próximo. Ele usou o exemplo do nosso próprio corpo: os olhos não enganam os pés, e as mãos ajudam todo o corpo a andar seguro. Da mesma forma, nós fazemos parte de uma mesma família em Deus. Quando dizemos a verdade uns aos outros, cuidamos uns dos outros com amor, fazendo com que todos vivam em paz, segurança e grande alegria no lar.', 'Imagine se os seus olhos dissessem para os seus pés que o chão está livre, mas houvesse um buraco ali. Você tropeçaria! No nosso lar e com os amigos, a mentira funciona como um tropeço que machuca a confiança. Quando você fala a verdade, mesmo quando sente medo ou comete um erro, você age como um abraço seguro que protege toda a família. Falar a verdade mostra que somos unidos pelo amor de Jesus, trazendo paz ao coração e fazendo nossa casa ser um lugar alegre e seguro.', 'Fale uma verdade com carinho para alguém da sua família antes de dormir.', 'A verdade nos une e faz o nosso lar brilhar com amor.', 'Hoje aprendemos em Efésios 4 que falar a verdade é como vestir uma roupa nova e limpa dada por Jesus.
Como fazemos parte de uma mesma família, a honestidade protege nossos passos e fortalece a confiança no lar.
Escolha falar a verdade com amor todos os dias!', NOW()),
('6f9aa6d6-c075-4cce-9baf-ba117f471819', 'honestidade', 'Honestidade', 'kids', 'teens', 8, 'Despindo a Mentira, Vivendo a Verdade', 'Efésios 4:22-25', 'O apóstolo Paulo escreveu aos cristãos da cidade de Éfeso com instruções práticas sobre a nova vida em Cristo. Ele explicou que seguir a Jesus exige uma mudança visível de atitude, comparável a tirar uma roupa velha e suja para vestir vestes novas e limpas. O velho modo de viver era marcado pelo engano e por costumes corrompidos, mas a nova natureza foi criada segundo Deus em verdadeira justiça e santidade. Por isso, a primeira ordem prática de Paulo foi clara: deixem totalmente a mentira e falem a verdade cada um com o seu próximo. O apóstolo lembrou àquela comunidade que todos pertenciam ao mesmo corpo. Assim como os membros de um corpo físico não trabalham para enganar uns aos outros, os seguidores de Cristo precisam da verdade para viver em paz e união genuína.', 'No dia a dia na escola ou em casa, mentir parece um atalho fácil para evitar castigos ou ser aceito pelos amigos. Contudo, a mentira destrói a confiança e enfraquece as relações, como uma perna que tenta enganar o próprio corpo ao caminhar. Falar a verdade, mesmo diante de erros ou pressões, gera paz e fortalece os laços em nossa família. Quando escolhemos a sinceridade, demonstramos que honramos a Deus e valorizamos as pessoas ao nosso redor.', 'Conte hoje aos seus pais uma verdade difícil que você estava evitando falar.', 'A verdade constrói pontes firmes onde a mentira só cria muros.', 'Em Efésios 4, aprendemos que a verdade deve guiar todas as nossas conversas.
Falar a verdade fortalece a confiança em casa e nos protege das pressões externas.
Hoje reafirmamos nosso compromisso de viver com total sinceridade em família.', NOW()),
('48581961-6d07-4dea-9673-48afa100e326', 'honestidade', 'Honestidade', 'kids', 'young_adults', 8, 'Despojando a Mentira, Vivendo a Verdade', 'Efésios 4:22-25', 'O apóstolo Paulo escreveu aos cristãos da cidade de Éfeso com instruções diretas sobre a transformação prática da vida com Cristo. Ele advertiu que era necessário abandonar a antiga conduta, marcada pelos enganos e costumes corrompidos do passado. Os crentes foram chamados a renovar a mente e a se revestir de uma nova natureza, criada por Deus em verdadeira justiça e santidade. Por essa razão, a primeira ordem prática de Paulo foi clara e urgente: deixar a mentira e falar a verdade cada um com o seu próximo. O apóstolo explicou a razão desse mandamento fundamental: todos os crentes pertencem ao mesmo corpo espiritual. Mentir para um irmão seria o mesmo que enganar a si próprio e ferir a própria comunidade. A comunhão cristã só poderia subsistir onde a sinceridade e a integridade fossem a base firme de todas as palavras e atitudes diárias.', 'Mentir destrói os laços de confiança e enfraquece o lar e as amizades. Como jovens que se preparam para as responsabilidades da vida adulta, vocês enfrentam a tentação de esconder erros ou exagerar fatos para evitar correções. No entanto, quem pertence a Cristo abandona o engano e escolhe falar a verdade em qualquer circunstância. A honestidade nas pequenas conversas diárias estabelece os limites morais que protegerão seu caráter no futuro. Quando a verdade reina dentro de casa, os relacionamentos se fortalecem, gerando segurança, honra mútua e respeito duradouro diante de Deus e dos homens.', 'Confesse hoje mesmo uma omissão ou mentira para seus pais com total sinceridade.', 'Falar a verdade constrói pontes indestrutíveis de confiança no lar.', 'Lição de hoje: Deixando a mentira nas relações (Efésios 4:22-25).
Somos membros uns dos outros e chamados a rejeitar o engano para viver em integridade.
A verdade sincera fortalece a confiança no lar e edifica amizades verdadeiras.', NOW()),
('d24e5646-6b35-469c-a202-17b50b04b636', 'honestidade', 'Honestidade', 'personal', 'adulto', 9, 'Integridade Visível e Prestação de Contas', '2 Coríntios 8:20-21', 'Ao organizar a generosa coleta financeira destinada aos irmãos necessitados da Judeia, o apóstolo Paulo tomou precauções rigorosas. Ele sabia que a confiança da igreja e a honra do evangelho estavam em jogo. Por isso, recusou-se a transportar os recursos sozinho, associando outros irmãos respeitados e nomeados pelas congregações para acompanharem a entrega. Paulo não se apoiou apenas em sua autoridade apostólica nem em sua reta intenção interior. Seu objetivo era prevenir qualquer acusação ou suspeita infundada quanto à gestão de valores vultosos. Ele compreendia que a integridade cristã exige mais do que aprovação divina no oculto; requer também um testemunho claro e irrepreensível diante dos olhos de todos. Ao agir com total transparência administrativa, o apóstolo estabeleceu um padrão perpétuo de zelo público e fidelidade no serviço sagrado.', 'Muitas vezes justificamos a falta de clareza em nossas ações afirmando que Deus conhece o nosso coração. Contudo, a maturidade cristã compreende que a honestidade deve ser evidente também diante dos homens. Transparência nos negócios, nas palavras e no trato financeiro protege o nosso testemunho e glorifica a Deus. Viver com integridade autêntica significa submeter-se à prestação de contas com prontidão, eliminando qualquer margem para dúvidas, desconfianças ou escândalos na sociedade.', 'Preste contas hoje de forma transparente sobre uma responsabilidade financeira ou profissional pendente.', 'A honestidade genuína é irrepreensível diante de Deus e dos homens.', 'A honestidade cristã vai além da consciência limpa com Deus: ela exige conduta transparente diante dos homens.
O apóstolo Paulo ensina que prestar contas previne escândalos e fortalece a confiança mútua.
Zelar pelo bom testemunho público é parte essencial da nossa fidelidade diária.', NOW()),
('edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'honestidade', 'Honestidade', 'kids', 'kids', 9, 'Brilhando a Verdade Como Água Limpa', '2 Coríntios 8:20-21', 'O apóstolo Paulo estava organizando uma grande ajuda com muitas moedas para abençoar famílias que passavam fome em Jerusalém. Como o valor era precioso, Paulo não quis levar essa oferta sozinho. Ele convidou amigos de confiança para caminharem juntos nessa viagem importante. Paulo ensinou aos cristãos de Corinto que devemos fazer o que é correto e bom não apenas diante dos olhos de Deus, que tudo vê no céu, mas também aos olhos de todas as pessoas na terra. Ele não queria deixar nenhuma dúvida sobre a honestidade do grupo. Por isso, tudo foi feito às claras, com alegria e transparência, como um riacho de água cristalina onde qualquer pessoa consegue enxergar as pedrinhas no fundo. Paulo mostrou que os servos de Deus cuidam com muito amor da verdade em cada detalhe.', 'Assim como um aquário de vidro limpinho permite ver os peixinhos nadando, a nossa vida deve ser clara para todo mundo ver a verdade. Quando você divide um brinquedo, cumpre o que prometeu ou mostra o troco correto para seus pais, você age com clareza. Deus ama ver que fazemos coisas certas no nosso quarto quando ninguém olha, mas Ele também fica feliz quando nossas atitudes mostram Jesus aos nossos amigos. Ser honesto diante de todos traz paz ao coração e espalha luz por onde passamos.', 'Mostre e compartilhe seus brinquedos hoje com clareza e alegria diante da família.', 'A honestidade transparente é uma luz que alegra a Deus e aos homens.', 'Noite 9: Transparência e Bom Exemplo!
Aprenda com o exemplo de Paulo que a honestidade deve brilhar tanto diante de Deus quanto diante das pessoas.
Viver com clareza inspira paz e alegria na família.', NOW()),
('fe5c5041-dce1-42b8-a877-8296ba8c721c', 'honestidade', 'Honestidade', 'kids', 'teens', 9, 'Integridade Diante de Deus e Homens', '2 Coríntios 8:20-21', 'O apóstolo Paulo estava organizando uma grande oferta entre as igrejas da Grécia e da Macedônia para socorrer os cristãos necessitados em Jerusalém. Grandes quantias de dinheiro estavam envolvidas, e Paulo sabia que a desconfiança alheia poderia manchar o testemunho do Evangelho. Em vez de administrar os recursos sozinho, ele convidou irmãos respeitados de outras congregações para viajar com ele e supervisionar cada entrega. Paulo escreveu aos coríntios que tomava esse cuidado rigoroso para evitar qualquer acusação ou dúvida sobre a honestidade do grupo. Ele ensinou que os servos de Cristo devem zelar pelo que é correto não apenas diante dos olhos de Deus, que tudo conhece em segredo, mas também de forma transparente aos olhos das outras pessoas. A liderança cristã exige clareza absoluta para que ninguém tenha motivos justos para suspeitar do caráter dos que servem a Deus.', 'Não basta saber no coração que você não fez nada de errado; a forma como você age na escola e com os amigos precisa ser clara e transparente. Se você cola em uma prova, esconde notas dos pais ou assume crédito por um trabalho que não fez em grupo, você perde a confiança das pessoas. Viver a fé cristã de verdade exige prestar contas, assumir erros e agir com tanta retidão que ninguém possa apontar o dedo para sua conduta. Integridade pública protege o seu testemunho diário.', 'Seja transparente hoje prestando contas de uma tarefa escolar ou responsabilidade doméstica sem omitir detalhes.', 'A verdadeira honestidade brilha tanto diante de Deus quanto diante dos homens.', 'Devocional Noite 9: Honestidade pública e transparência.
Paulo nos ensina em 2 Coríntios 8:20-21 a zelar pelo que é certo perante Deus e as pessoas.
Integridade real exige prestar contas e manter uma conduta transparente nos estudos e nas amizades.', NOW()),
('8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'honestidade', 'Honestidade', 'kids', 'young_adults', 9, 'Integridade Diante de Deus e Homens', '2 Coríntios 8:20-21', 'O apóstolo Paulo organizava uma grande coleta entre as igrejas da Grécia e da Macedônia para socorrer os cristãos necessitados de Jerusalém. Ciente da enorme responsabilidade de manusear aquela quantia substancial, Paulo recusou conduzir o dinheiro sozinho ou em segredo. Ele designou irmãos honrados e comprovados na fé, escolhidos pelas próprias igrejas, para acompanharem todo o trajeto da entrega. O apóstolo queria eliminar qualquer brecha para fofocas, desconfianças ou acusações sobre o uso dos fundos sagrados. Para Paulo, não bastava ter a consciência limpa perante Deus; era indispensável agir com total clareza perante a comunidade. Ele estabeleceu um padrão elevado de administração, demonstrando que a verdadeira liderança cristã cuida do que é correto tanto aos olhos divinos quanto diante do julgamento dos homens.', 'Viver com retidão exige mais do que boas intenções secretas; requer transparência ativa nas decisões cotidianas. Quando você lida com dinheiro, compromissos escolares, amizades ou futuras responsabilidades profissionais, a clareza de suas atitudes protege seu caráter e glorifica a Deus. Não basta dizer que seu coração é puro se suas práticas geram dúvidas legítimas nos outros. Assumir a prestação de contas com seus pais e líderes constrói uma reputação sólida e inegociável. A integridade que honra o Senhor resiste à luz do dia e serve de modelo para toda a sociedade.', 'Preste contas hoje aos seus pais sobre seus gastos e horários com clareza.', 'A verdadeira retidão brilha aos olhos de Deus e da sociedade.', 'A integridade cristã exige transparência visível. Assim como Paulo cuidou da administração da igreja prestando contas abertamente, somos chamados a viver com retidão diante de Deus e dos homens, construindo um testemunho irrepreensível.', NOW()),
('7ff05bfa-6188-49f5-b69d-d19e44445c15', 'honestidade', 'Honestidade', 'personal', 'adulto', 10, 'A Firmeza da Consciência Pura', 'Atos 24:14-16', 'Diante do governador Félix em Cesareia, o apóstolo Paulo enfrentava acusações graves e injustas trazidas pelos líderes religiosos de Jerusalém. Em um ambiente hostil, cercado por intrigas políticas e risco de morte, muitos recorreriam à lisonja ou à omissão da verdade para salvar a própria pele. Paulo, contudo, manteve uma postura serena e inabalável. Ele admitiu com clareza servir ao Deus de seus pais conforme o Caminho, crendo fielmente nas Escrituras e na ressurreição dos mortos. Sem rodeios ou desculpas convenientes, ele declarou seu princípio de vida: esforçar-se continuamente para ter uma consciência limpa, sem ofensa tanto para com Deus quanto para com os homens. Sob a mais severa pressão pública, a integridade de Paulo permaneceu intacta. Seu testemunho não dependia das circunstâncias externas favoráveis, mas da sua inegociável fidelidade ao Senhor e ao próximo até o fim da sua jornada terrena.', 'Viver com integridade exige autogoverno diário e constante vigilância interior. Manter a consciência limpa diante de Deus e das pessoas não é fruto do acaso, mas de uma decisão deliberada de recusar atalhos, mentiras convenientes e meias-verdades. Quando você é colocado sob pressão no trabalho, na família ou nas finanças, a tentação de flexibilizar princípios se torna real. Contudo, a verdadeira paz reside na certeza de que suas palavras e ações estão alinhadas com a retidão divina. Escolha a verdade inegociável, pois uma consciência irrepreensível é o alicerce mais sólido para qualquer vida madura.', 'Avalie suas decisões de hoje e corrija imediatamente qualquer desvio da verdade.', 'Uma consciência limpa diante de Deus sustenta qualquer pessoa sob pressão.', 'Manter uma consciência limpa perante Deus e as pessoas exige fidelidade inegociável.
Mesmo sob intensa pressão, Paulo escolheu a verdade e a retidão prática.
Cultive hoje o autogoverno necessário para viver com integridade inabalável.', NOW()),
('2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'honestidade', 'Honestidade', 'kids', 'kids', 10, 'Coração Limpo Como Água Cristalina', 'Atos 24:14-16', 'O apóstolo Paulo estava diante de um poderoso governador chamado Félix. Muitas pessoas diziam coisas falsas e ruins sobre ele para tentar assustá-lo. Paulo, porém, continuou calmo e firme como uma árvore forte que não cai com o vento. Ele olhou nos olhos do governador e falou apenas a pura verdade. Paulo explicou que acreditava em tudo o que Deus havia ensinado e confiava na promessa da ressurreição. Ele disse com muita coragem que sempre se esforçava para manter o seu coração limpo e a sua consciência sem mancha diante de Deus e de todas as pessoas. Nenhuma mentira ou ameaça conseguia fazer Paulo mudar de ideia. Ele preferiu ser honesto e fiel até o fim, sabendo que o Senhor cuidava de cada um dos seus passos.', 'Ter a consciência limpa é como olhar para um riacho de água bem transparente, onde conseguimos ver até as pedrinhas no fundo sem nenhuma sujeira. Quando falamos a verdade mesmo com medo, o nosso coração descansa em paz como um passarinho seguro no ninho. Paulo nos ensina que a honestidade nos dá uma força especial que ninguém pode tirar. Escolher fazer o que é certo agrada a Deus e enche a nossa casa de alegria verdadeira todos os dias.', 'Dizer sempre a verdade hoje, mesmo quando for difícil ou der medo.', 'Quem anda na verdade tem o coração leve e em paz.', 'Noite 10: Firmeza e Consciência Limpa!
Aprenda com o exemplo de Paulo a manter a honestidade mesmo sob pressão.
Ter o coração puro diante de Deus traz paz e verdadeira alegria ao lar.
Fale a verdade com coragem hoje e sempre!', NOW()),
('60b5a1b2-649a-4ceb-8d35-097638898055', 'honestidade', 'Honestidade', 'kids', 'teens', 10, 'Consciência Limpa Sob Toda Pressão', 'Atos 24:14-16', 'O apóstolo Paulo estava preso no tribunal em Cesareia diante do governador romano Félix. Acusações graves e mentirosas foram lançadas contra ele por líderes religiosos influentes que queriam sua condenação a qualquer custo. Paulo teve a oportunidade de se defender, mas não recorreu a mentiras, lisonjas ou meias-verdades para tentar escapar da prisão. Com total serenidade, ele admitiu abertamente que servia ao Deus de seus antepassados e acreditava fielmente nas Escrituras e na ressurreição dos mortos. Paulo declarou com firmeza que seu maior compromisso de vida era manter sempre uma consciência limpa diante de Deus e de todas as pessoas, sem ofensas e sem duplicidade. Mesmo cercado de inimigos poderosos e arriscando sua liberdade, a verdade permaneceu inegociável em sua boca. Sua integridade no julgamento revelou que a fidelidade a Deus vale mais do que a aprovação dos homens.', 'Manter a honestidade quando todos ao redor pressionam para trapacear, mentir ou fingir exige coragem real. Na escola, no grupo de amigos ou nas redes sociais, o medo de ser excluído pode nos tentar a esconder a verdade. No entanto, ter uma consciência limpa diante de Deus traz uma paz interior que nenhuma popularidade passageira pode oferecer. A integridade verdadeira não muda de acordo com o ambiente ou a conveniência. Escolha a verdade mesmo quando parecer mais difícil, pois ela preserva seu caráter e honra ao Senhor.', 'Diga a verdade em uma situação difícil hoje, sem inventar desculpas para se proteger.', 'Uma consciência limpa diante de Deus vale mais que qualquer aprovação humana.', 'Noite 10: Consciência Limpa Sob Toda Pressão.
Assim como Paulo diante do governador, aprendemos que a integridade não se negocia por medo ou aceitação social.
Manter a verdade diante de Deus e dos homens gera paz duradoura e caráter firme.', NOW()),
('f882ac49-823c-411f-980e-da5142940e77', 'honestidade', 'Honestidade', 'kids', 'young_adults', 10, 'Consciência Limpa Sob Qualquer Pressão', 'Atos 24:14-16', 'O apóstolo Paulo estava preso em Cesareia, sob falsas acusações diante do governador romano Félix. Diante de juízes poderosos e acusadores furiosos, ele não recuou nem recorreu a mentiras para salvar sua própria pele. Paulo declarou abertamente que servia ao Deus de seus pais conforme o Caminho de Cristo, crendo firmemente na ressurreição dos justos e injustos. Sua defesa não se baseou em ardis humanos, mas em sua conduta irrepreensível. Ele afirmou categoricamente seu compromisso inegociável: esforçar-se sempre para ter uma consciência limpa diante de Deus e diante de todos os homens. Sob o risco iminente de condenação severa, Paulo demonstrou que a verdade divina vale mais do que a aprovação do mundo ou o alívio imediato de uma punição. Sua fidelidade inabalável revelou a força espiritual de quem vive sem nada a esconder.', 'Viver com a consciência limpa exige coragem diária, especialmente quando mentir parece o caminho mais fácil para evitar punições ou ser aceito pelo grupo. O futuro de um jovem é construído pelas escolhas silenciosas feitas no quarto, nas conversas digitais e nas provas da escola. Paulo nos ensina que a verdadeira integridade resiste a qualquer pressão externa porque teme a Deus antes dos homens. Quando você decide não negociar seus princípios morais em segredo, sua fé ganha autoridade sólida. Escolher a verdade custa caro no momento, mas preserva a paz interior para o resto da vida.', 'Assuma hoje a verdade sobre um erro oculto diante de Deus e da família.', 'Uma consciência limpa é o maior escudo contra qualquer acusação do mundo.', 'Noite 10: Paulo nos ensina que manter a integridade inabalável sob pressão é viver com a consciência limpa diante de Deus e dos homens. A verdadeira honra se constrói em escolhas privadas sinceras. Decida hoje permanecer firme na verdade.', NOW());

INSERT INTO "public"."dev_questions" ("id", "lesson_id", "question_text", "display_order") VALUES
('444f2335-6d52-45d9-b9a6-889eedeb151c', 'a1a87603-fb01-4373-b3af-4aa71ca1db45', 'De que maneira Zaqueu demonstrou publicamente que sua transformação era sincera e concreta?', 1),
('dad0ba76-7446-4648-8d4f-81aed7e6cb93', 'a1a87603-fb01-4373-b3af-4aa71ca1db45', 'Em quais áreas da administração da sua vida você sente dificuldade em reconhecer e corrigir falhas?', 2),
('98808596-f1bd-472c-b34c-36aec2ce1a48', 'a1a87603-fb01-4373-b3af-4aa71ca1db45', 'Que passo prático de reparação ou acerto você precisa dar para manter a consciência limpa?', 3),
('5897c76e-395a-4131-ac44-7888a3204fa3', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'O que Zaqueu prometeu fazer depois que Jesus entrou em sua casa?', 1),
('0fb93876-af3b-4645-aada-5a87b56c5bc5', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'Como você se sente quando precisa admitir um erro e pedir desculpas?', 2),
('40e8e7a7-e6ca-4eef-b2a2-f84b87c1d521', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'Que atitude prática podemos ter para consertar algo que fizemos de errado?', 3),
('dd7e82a5-4147-4e74-9766-2ff313a660b4', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'O que motivou Zaqueu a devolver quatro vezes mais a quem ele havia prejudicado?', 1),
('b342ba71-9963-4710-9d49-e7f92c5b2df5', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'Em quais situações na escola ou em casa sentimos mais dificuldade em assumir e consertar uma falha?', 2),
('181ebba3-5046-4e6a-8a79-8c62c9097f36', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'Que atitude prática você pode tomar hoje para desfazer um mal-entendido ou reparar um erro?', 3),
('3b69e0fc-b562-44f7-b329-b0715ad2fbf1', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'O que Zaqueu prometeu fazer para reparar os prejuízos causados aos outros?', 1),
('fabb4488-6f4c-4aa4-8801-c6e668d48af9', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'Em quais situações do seu dia a dia é mais difícil admitir um engano e consertá-lo?', 2),
('cfbd2405-1bee-436b-8a9f-36c6d181b005', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'Que passo concreto de restituição ou pedido de perdão você precisa dar nesta semana?', 3),
('08751e1c-8f32-4021-8a5a-3e89cdc2c1a7', '3759048f-684b-4335-8159-138ec6096faa', 'Qual razão o apóstolo Paulo apresenta para que falemos a verdade uns aos outros?', 1),
('9ecc62e4-4f99-4279-b8d5-af72ae42d0de', '3759048f-684b-4335-8159-138ec6096faa', 'Em quais momentos cotidianos você sente a tentação de omitir ou suavizar a verdade?', 2),
('7c6558c6-6e52-4923-a3b3-f65171f814ec', '3759048f-684b-4335-8159-138ec6096faa', 'Que passo concreto você dará para cultivar maior sinceridade em seus diálogos diários?', 3),
('959abef7-17ab-4e01-b245-f432c17819d8', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'Segundo o apóstolo Paulo, por que as partes do corpo precisam cooperar falando a verdade?', 1),
('614c94e8-e192-451d-98b6-d6b7ace877af', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'Como você se sente no coração quando alguém que você ama conta uma mentira?', 2),
('761cd3f1-1fbb-4e23-89b0-940886d69579', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'O que podemos fazer juntos para ter coragem de falar a verdade quando errarmos?', 3),
('53aaba4a-1c5b-45ba-8363-6d6e73b993ca', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'Por que o apóstolo Paulo afirma que devemos falar a verdade ao nosso próximo?', 1),
('3091f918-ea99-47c8-abfa-2a849122909e', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'Em quais situações na escola ou em casa você sente maior tentação de mentir ou esconder algo?', 2),
('6f549e35-ab6e-4127-8e27-125603569a2c', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'O que nossa família pode fazer para tornar mais fácil falar a verdade, mesmo quando erramos?', 3),
('b7e034bc-2f2c-4038-ad7e-007fda932918', '48581961-6d07-4dea-9673-48afa100e326', 'Por que o apóstolo Paulo afirma que devemos abandonar a mentira e falar a verdade ao próximo?', 1),
('8caa3885-dcfa-4151-8738-59b51bd88775', '48581961-6d07-4dea-9673-48afa100e326', 'Em quais momentos do dia a dia você sente maior tentação de omitir a verdade para evitar consequências?', 2),
('94eff046-cb15-4067-a8ce-cf478cde06e7', '48581961-6d07-4dea-9673-48afa100e326', 'Que atitude prática você tomará hoje para que a verdade prevaleça em todas as suas conversas em família?', 3),
('85c3c892-8b29-4320-b726-0528dffa4cc0', 'd24e5646-6b35-469c-a202-17b50b04b636', 'Por que o apóstolo Paulo fez questão de envolver outros irmãos na administração daquela oferta?', 1),
('62a4c449-2109-4865-a316-1018fa63f0e6', 'd24e5646-6b35-469c-a202-17b50b04b636', 'Em quais áreas de sua vida cotidiana você sente maior resistência em prestar contas abertamente?', 2),
('ba11ab42-496f-41a0-b1bb-86bfa4c73b57', 'd24e5646-6b35-469c-a202-17b50b04b636', 'Que atitude concreta você tomará hoje para tornar suas decisões e compromissos mais claros aos outros?', 3),
('90f4daad-40f8-45bc-9dfa-381543ca2d68', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'Por que Paulo levou amigos de confiança com ele para entregar as ofertas?', 1),
('5e03fc68-13de-4adb-a6cd-e119d558377d', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'Como você se sente quando vê que tudo está claro e ninguém precisa esconder nada?', 2),
('e33ee3c7-b893-4fa3-b71c-ebed687bbc74', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'O que podemos fazer hoje para mostrar atitudes sinceras e transparentes aos outros?', 3),
('94a88f2c-5498-4896-8832-bce710809b5f', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'Por que o apóstolo Paulo pediu que outros irmãos acompanhassem a entrega das ofertas?', 1),
('da6c5349-d8bf-4e67-8c89-5245b192dc40', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'Em quais situações na escola ou nas amizades você sente tentação de agir sem total transparência?', 2),
('7c259305-2398-4117-811c-4738fa7c6553', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'O que você pode fazer esta semana para demonstrar mais responsabilidade e confiança aos seus pais e professores?', 3),
('e1efac8d-88d5-4636-b3e3-ce8d8916fd77', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Por que Paulo escolheu outros irmãos para administrar a oferta em vez de fazer isso sozinho?', 1),
('ff393dd3-6426-40b0-a986-cc4010acca25', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Em quais áreas da sua rotina você sente mais dificuldade de ser totalmente transparente com seus pais?', 2),
('3f4f783c-c0c1-4573-a3aa-4393b27b6264', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Que hábito de prestação de contas você pode adotar a partir de hoje para evitar desconfianças?', 3),
('6d9464b2-1b3f-43d6-b192-bd0b1b3dd33a', '7ff05bfa-6188-49f5-b69d-d19e44445c15', 'Qual era o compromisso diário que Paulo declarou diante do governador Félix?', 1),
('8e11b12f-e824-440b-81b2-16133a2401cb', '7ff05bfa-6188-49f5-b69d-d19e44445c15', 'Em quais momentos de pressão você sente maior tentação de comprometer sua integridade?', 2),
('b8a07367-6de7-49b9-a2e8-4b7e7c6df5ff', '7ff05bfa-6188-49f5-b69d-d19e44445c15', 'Que atitude prática você tomará hoje para alinhar suas ações à verdade inegociável?', 3),
('4e958276-7fdb-400b-bbe6-f4120b11c00b', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'Por que Paulo não teve medo de dizer a verdade diante do governador Félix?', 1),
('2913d953-0d19-4fd3-8193-419803e14da7', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'Como você se sente por dentro quando fala a verdade em vez de esconder algo?', 2),
('f7c2bae8-f195-4096-829e-07b7da10ff77', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'O que podemos fazer quando sentirmos vontade de mentir para não levar bronca?', 3),
('af14ec0f-a865-468d-9578-5938840ad718', '60b5a1b2-649a-4ceb-8d35-097638898055', 'O que Paulo priorizou manter limpa diante de Deus e dos homens durante seu julgamento?', 1),
('8dc2039b-8b2c-449b-9343-30a213bde48a', '60b5a1b2-649a-4ceb-8d35-097638898055', 'Em quais situações você sente maior tentação de mentir para ser aceito ou evitar problemas?', 2),
('3786bff1-2a18-41fc-b5ec-13fa2c4a63f5', '60b5a1b2-649a-4ceb-8d35-097638898055', 'Que atitude prática você tomará a partir de hoje para não negociar a verdade com seus amigos?', 3),
('f607253a-14f6-4f19-8669-fd7500baea1d', 'f882ac49-823c-411f-980e-da5142940e77', 'Qual era o compromisso inegociável que Paulo manteve mesmo correndo risco de morte diante do governador?', 1),
('c6280485-1f7f-49bb-bead-fd1303bb2f8d', 'f882ac49-823c-411f-980e-da5142940e77', 'Em quais momentos você sente maior tentação de esconder a verdade para se proteger da reprovação alheia?', 2),
('d3c1cbc8-dfb2-41b5-a926-eaea18f38a6b', 'f882ac49-823c-411f-980e-da5142940e77', 'Qual limite moral prático você precisa estabelecer hoje para manter sua consciência blindada contra as pressões do dia a dia?', 3);

INSERT INTO "public"."dev_prayers" ("id", "lesson_id", "role", "text_content", "display_order") VALUES
('87346d77-3fa0-44bd-b0a0-9813843b7600', 'a1a87603-fb01-4373-b3af-4aa71ca1db45', 'Individual', 'Senhor, sonda o meu coração e revela onde falhei com a justiça e a honestidade. Dá-me coragem e prontidão para reparar danos, pagar o que devo e agir com total retidão diante de Ti e das pessoas. Que a Tua verdade governe as minhas escolhas materiais e morais. Amém.', 1),
('72b96845-00f4-424b-9885-6309495d6fc7', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'Pai', 'Senhor, ensina-me a ser exemplo de retidão e a ter coragem para consertar meus erros diante da minha família.', 1),
('82bb1362-163e-4b45-8b4f-8fa2306974b0', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'Filho', 'Papai do Céu, me ajuda a sempre devolver o que não é meu e a dizer a verdade sem medo.', 2),
('e9dbbb68-e696-4f89-b635-f68803e738b1', '3e827ef6-0d0e-4202-a727-bc761fc1e368', 'Juntos', 'Amado Jesus, transforma o nosso lar em um lugar de justiça, perdão e honestidade todos os dias. Amém.', 3),
('644f307d-2f50-46cf-9a1b-ff80aea9e3f5', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'Pai', 'Senhor, dá-me humildade para reconhecer minhas falhas e coragem para ensinar meus filhos a reparar erros com retidão.', 1),
('48976ce6-acba-4065-a2f3-30a9a50a584d', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'Filho', 'Jesus, ajuda-me a não fugir das consequências dos meus atos e a consertar o que fiz de errado com meus amigos e familiares.', 2),
('c0f186af-6255-47f7-aaf1-356069258778', '8b983b9d-9d83-4e15-85c0-8742f695f759', 'Juntos', 'Pai Celestial, que a nossa casa viva a alegria da honestidade que restaura a paz e honra o Teu santo nome. Amém.', 3),
('e3717860-af2c-4c75-8146-4f5d0a9c3880', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'Pai', 'Senhor, dá-me sabedoria para ensinar meus filhos pelo exemplo de retidão e restituição.', 1),
('695469d9-b3be-4e62-9a0e-da77d30c8873', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'Filho', 'Pai celeste, conceda-me coragem para admitir minhas falhas e consertar os danos que causei.', 2),
('4888d27e-db4f-45d1-bab0-2337d1a67de4', 'c34441fb-8e9e-4433-8ece-4dfa022ba911', 'Juntos', 'Deus eterno, que a nossa casa seja marcada pela transparência, justiça e honestidade sincera. Amém.', 3),
('24997a55-35c6-47ff-92df-0fe3a5057008', '3759048f-684b-4335-8159-138ec6096faa', 'Individual', 'Senhor Deus, purifica os meus lábios e o meu coração de toda falsidade. Dá-me coragem para falar a verdade com amor, mantendo a firmeza e a retidão em minhas relações diárias. Que a integridade guie cada palavra minha. Amém.', 1),
('9f37a0af-8b6d-4097-a24d-e242c1868445', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'Pai', 'Senhor, ajuda-me a ser um exemplo de sinceridade e a guiar nossa casa na Tua luz.', 1),
('fbe77f8b-8a24-42fc-809b-5c4c1e3a8621', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'Filho', 'Jesus, me dê coragem para falar sempre a verdade e cuidar da minha família.', 2),
('76f1e525-2578-454b-8df6-800ac023119d', 'cb38f116-e08e-4b83-bbda-a1ffd6fad9b8', 'Juntos', 'Pai do Céu, que a verdade e o amor estejam sempre presentes em nosso lar. Amém.', 3),
('b2186ce6-ef08-481a-8c30-5bc042a889e0', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'Pai', 'Senhor, ajuda-me a liderar meu lar com transparência e paciência para acolher a verdade sempre.', 1),
('dfd23c81-dd1c-4c08-9c15-2de3e9885a0e', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'Filho', 'Deus, dá-me coragem para falar a verdade e rejeitar a mentira diante dos meus amigos e da família.', 2),
('c3e69d44-2831-42ee-9020-2135c6dda7f7', '6f9aa6d6-c075-4cce-9baf-ba117f471819', 'Juntos', 'Pai celestial, fortalece nossa união através da verdade e faz da nossa casa um lugar de confiança mútua. Amém.', 3),
('3410220b-e431-4310-91cb-e928ba991bb3', '48581961-6d07-4dea-9673-48afa100e326', 'Pai', 'Senhor, ensina-me a ser um exemplo irrepreensível de verdade para guiar minha família no caminho da retidão.', 1),
('cb127b6d-965f-4cad-82b2-91c5b2e93e2e', '48581961-6d07-4dea-9673-48afa100e326', 'Filho', 'Deus, dá-me coragem para sempre falar a verdade aos meus pais, mesmo quando errar ou sentir medo.', 2),
('42f4dc26-45c4-45e6-8ad2-2e1cd5ae887c', '48581961-6d07-4dea-9673-48afa100e326', 'Juntos', 'Pai Celestial, ajuda nossa casa a rejeitar todo engano e a viver unida pela sinceridade e integridade. Amém.', 3),
('8016124c-c8d2-4e04-820e-aa26188e43f2', 'd24e5646-6b35-469c-a202-17b50b04b636', 'Individual', 'Senhor Deus, concede-me sabedoria e retidão para agir com total transparência em todas as minhas responsabilidades. Que a minha conduta seja irrepreensível tanto aos Teus olhos quanto diante das pessoas ao meu redor. Livra-me do orgulho de agir isoladamente e ensina-me a valorizar a prestação de contas, preservando a honra do Teu nome em cada detalhe do meu trabalho e da minha vida. Amém.', 1),
('cdae47da-e069-4dda-a9c6-78833a57a325', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'Pai', 'Senhor, ajuda-nos a liderar nosso lar com integridade visível e honrar Teu nome perante todos.', 1),
('6f53c312-e8d8-461b-adc9-2fcedda7607f', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'Filho', 'Papai do Céu, quero ser sincero e fazer as coisas certas para todos verem Tua luz.', 2),
('e024d209-5d3d-45a2-bc9c-7c0f70b0b6fc', 'edf8c82f-3bf9-4ee3-a0eb-7f69bfc13e44', 'Juntos', 'Que nossa família seja transparente e alegre como água limpa que reflete Teu amor. Amém.', 3),
('15416f83-ca09-4bb1-8928-59e9df5fcd24', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'Pai', 'Senhor, ajuda-me a liderar meu lar com transparência e a ser um exemplo visível de retidão no trabalho e na família.', 1),
('8858a44a-3bb3-43cd-912a-ac2661db0cfa', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'Filho', 'Pai do Céu, livra-me do engano e da pressão dos colegas, para que minhas ações na escola tragam honra ao Teu nome.', 2),
('074da1f0-fb2a-4e4e-add2-27fe62a0d683', 'fe5c5041-dce1-42b8-a877-8296ba8c721c', 'Juntos', 'Deus eterno, firma nossa família na honestidade absoluta, diante dos Teus olhos e de todas as pessoas. Amém.', 3),
('d931fc6a-e43c-4d03-99ad-d46666cd4f3d', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Pai', 'Senhor, ajuda-me a liderar com exemplo límpido, ensinando transparência em cada decisão da nossa casa.', 1),
('89c93905-b41c-46d7-bd22-5b94f1f86bff', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Filho', 'Deus, dá-me coragem para agir às claras, prestando contas com sinceridade e honrando a Tua palavra.', 2),
('1588ad78-7cb9-401a-b839-6c241f7052cf', '8ff26d87-6ccc-47da-b1e8-3ee4917eeef9', 'Juntos', 'Pai celestial, firma nossa família na retidão, para que nosso testemunho seja irrepreensível diante de todos. Amém.', 3),
('f5282ca3-2b40-4057-a5e5-275029dc1ff5', '7ff05bfa-6188-49f5-b69d-d19e44445c15', 'Individual', 'Senhor Deus, concede-me a firmeza necessária para manter minha consciência limpa em todas as situações. Ensina-me a não ceder ao medo ou à conveniência quando os princípios da verdade forem provados. Que o meu testemunho seja coerente, sincero e fiel diante de Ti e dos homens, hoje e sempre. Amém.', 1),
('efcb6bf7-efb8-4679-b820-e89279cc0e69', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'Pai', 'Senhor, ajuda-nos a ensinar e viver a verdade com amor e coragem todos os dias.', 1),
('85486fa9-62c4-4e9d-a239-8f5371cffa43', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'Filho', 'Papai do Céu, me ajude a ser corajoso e falar sempre a verdade sem medo.', 2),
('5ca2c283-0cb6-42dd-8d09-dcd5266055ec', '2cd31867-0cf5-421e-a9e6-6b95f2e2d33b', 'Juntos', 'Senhor, guarde nossa família para termos sempre um coração limpo e sincero. Amém.', 3),
('74f11622-34ef-4c11-bd47-e5ae0fd884b8', '60b5a1b2-649a-4ceb-8d35-097638898055', 'Pai', 'Senhor, dá-nos coragem para viver com retidão e ensinar a verdade sem temer pressões externas.', 1),
('eac6be81-9848-4e31-8a79-f2aa7339ee37', '60b5a1b2-649a-4ceb-8d35-097638898055', 'Filho', 'Pai celestial, ajuda-me a manter minha consciência limpa e a nunca mentir para agradar outras pessoas.', 2),
('861432d3-bddf-466e-a2dc-10129bd5bdbc', '60b5a1b2-649a-4ceb-8d35-097638898055', 'Juntos', 'Que a verdade de Cristo guie nossas palavras e atitudes em qualquer lugar onde estivermos. Amém.', 3),
('439ce0d3-f11b-43ef-8ef2-cb54a594d008', 'f882ac49-823c-411f-980e-da5142940e77', 'Pai', 'Senhor, capacita-me a liderar meu lar com retidão e a incentivar meu filho a amar a verdade.', 1),
('1dff561c-90f3-48c3-8a81-0456b57ee067', 'f882ac49-823c-411f-980e-da5142940e77', 'Filho', 'Pai celeste, dá-me firmeza para nunca negociar meus valores, mantendo minha consciência limpa em secreto.', 2),
('f3ba5d1b-2f88-4d53-8261-4280f001c7b3', 'f882ac49-823c-411f-980e-da5142940e77', 'Juntos', 'Deus eterno, guarda a nossa família em Tua santidade para que vivamos com integridade até o fim. Amém.', 3);

